/**
 * Author:  VSIANIK
 * Created: Sep 7, 2019
 */

CREATE TABLE TB_LEAVE_NOTIFICATION
(
  FINYEAR       NUMBER                          NOT NULL,
  FINMONTH      VARCHAR2(15 BYTE)		NOT NULL,
  COMPANY       VARCHAR2(255 BYTE)              NOT NULL,
  CARDNO        VARCHAR2(15 BYTE)               NOT NULL,
  SUPERVISOR_CARDNO  VARCHAR2(15 BYTE)		NOT NULL,
  START_DATE        DATE,
  END_DATE          DATE,
  REASON	VARCHAR2(255 BYTE),
  LEAVE_TYPE	VARCHAR2(255 BYTE) 		NOT NULL,
  LEAVEDAY      NUMBER,
  SALDAY        NUMBER,
  REQUEST_DATE  DATE
)



CREATE TABLE TB_CONN_WORKR_SUPRVISOR
(
  COMPANY       VARCHAR2(255 BYTE)              NOT NULL,
  CARDNO        VARCHAR2(15 BYTE)               NOT NULL,
  SUPERVISOR_CARDNO  VARCHAR2(15 BYTE)		NOT NULL
)




-- INSERT DATA IN TABLE

INSERT INTO TB_LEAVE_NOTIFICATION 
(
	FINYEAR,
	FINMONTH,
	COMPANY,
	CARDNO,
	SUPERVISOR_CARDNO,
	START_DATE,
	END_DATE,
	LEAVE_TYPE,
	LEAVEDAY,
	SALDAY,
	REASON,
	REQUEST_DATE
) VALUES 
(2019,'May','Best Wool Sweaters Ltd.','PR-1001','DS-10002',
TO_DATE('01/10/2019', 'DD/MM/YYYY'),
TO_DATE('01/11/2019', 'DD/MM/YYYY'),
'Casual',1,1,'PERSONAL PROBLEM',
TO_DATE('01/04/2019', 'DD/MM/YYYY')
);