/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportgenerator.view;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.border.EmptyBorder;
import reportgenerator.view.subwindow.*;

/**
 *
 * @author Anik
 */
public class MainWorkingWindow extends javax.swing.JFrame {

    //private String savingLoc = "D:\\";
    private String savingLoc = "\\\\192.168.1.210\\monthly_online_bill_and_quotation\\";
    private String configComapnyListUrl = "setup\\CompanyName.txt";
    private String configPendingBillList = "setup\\PandingList.txt";
    private String configSetupDatabase = "setup\\ConnectionSetup.properties";

    private int hightOfMainPen = 0;
    private int widthOfMainPen = 0;
    private int componentSize = 2;
    private int subPenTopBorder = 10;
    private int subPenBottomBorder = 10;
    private int subPenLeftBorder = 20;
    private int subPenRightBorder = 20;

    /**
     * Creates new form MainWorkingWindow
     */
    public MainWorkingWindow() {

        initComponents();
        mainPen.setLayout(new BorderLayout(50, 50));

//        Dimension DimMax = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setMaximumSize(DimMax);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hightOfMainPen = mainPen.getHeight();
        widthOfMainPen = mainPen.getWidth();

//        lblShowCompany.setLocation(0,(this.getHeight()/2));
//        lblShowLogo.setLocation(10,this.getHeight());
        //subPenLeftBorder=(widthOfMainPen/2)-(widthOfMainPen/4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penEntryDoctorInfo = new javax.swing.JInternalFrame();
        subPenOfEntryDoctorInfo = new javax.swing.JPanel();
        penEntryPatientInfo = new javax.swing.JInternalFrame();
        subPenOfEntryPatientInfo = new javax.swing.JPanel();
        penEntrySeviceInfo = new javax.swing.JInternalFrame();
        subPenOfEntryServiceInfo = new javax.swing.JPanel();
        penEntryRoomInfo = new javax.swing.JInternalFrame();
        subPenOfEntryRoomInfo = new javax.swing.JPanel();
        penEntryDoctorAppointment = new javax.swing.JInternalFrame();
        subPenOfEntryDoctorAppointment = new javax.swing.JPanel();
        penEntryRoomBooking = new javax.swing.JInternalFrame();
        subPenOfEntryRoomBooking = new javax.swing.JPanel();
        penEntryPatientAdmmisson = new javax.swing.JInternalFrame();
        subPenOfEntryPatientAdmmisson = new javax.swing.JPanel();
        penShowDoctorAppointment = new javax.swing.JInternalFrame();
        subPenOfShowDoctorAppointment = new javax.swing.JPanel();
        mainPen = new javax.swing.JPanel();
        lblShowCompany = new javax.swing.JLabel();
        lblShowReord = new javax.swing.JLabel();
        lblShowReord2 = new javax.swing.JLabel();
        lblShowReord3 = new javax.swing.JLabel();
        lblShowReord4 = new javax.swing.JLabel();
        lblShowReord5 = new javax.swing.JLabel();
        lblCopyRightTeg = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuEntry = new javax.swing.JMenu();
        manuItemEntryAdvanceAmount = new javax.swing.JMenuItem();
        manuItemSubmitPanddingBill = new javax.swing.JMenuItem();
        manuItemIncomeAndCost = new javax.swing.JMenuItem();
        manuItemIncomeAndCost3 = new javax.swing.JMenuItem();
        menuEntry2 = new javax.swing.JMenu();
        manuItemEntryAdvanceAmount2 = new javax.swing.JMenuItem();
        manuItemIncomeAndCost5 = new javax.swing.JMenuItem();
        manuItemIncomeAndCost4 = new javax.swing.JMenuItem();
        menuEntry1 = new javax.swing.JMenu();
        manuItemIncomeAndCost6 = new javax.swing.JMenuItem();
        manuItemIncomeAndCost8 = new javax.swing.JMenuItem();
        manuItemIncomeAndCost9 = new javax.swing.JMenuItem();

        penEntryDoctorInfo.setBackground(new java.awt.Color(204, 204, 204));
        penEntryDoctorInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryDoctorInfo.setClosable(true);
        penEntryDoctorInfo.setMaximizable(true);
        penEntryDoctorInfo.setResizable(true);
        penEntryDoctorInfo.setTitle("Entry Doctor Info");
        penEntryDoctorInfo.setToolTipText("Entry Doctor Info");
        penEntryDoctorInfo.setVisible(true);
        penEntryDoctorInfo.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryDoctorInfoInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryDoctorInfo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryDoctorInfoLayout = new javax.swing.GroupLayout(subPenOfEntryDoctorInfo);
        subPenOfEntryDoctorInfo.setLayout(subPenOfEntryDoctorInfoLayout);
        subPenOfEntryDoctorInfoLayout.setHorizontalGroup(
            subPenOfEntryDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryDoctorInfoLayout.setVerticalGroup(
            subPenOfEntryDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryDoctorInfoLayout = new javax.swing.GroupLayout(penEntryDoctorInfo.getContentPane());
        penEntryDoctorInfo.getContentPane().setLayout(penEntryDoctorInfoLayout);
        penEntryDoctorInfoLayout.setHorizontalGroup(
            penEntryDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryDoctorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryDoctorInfoLayout.setVerticalGroup(
            penEntryDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryDoctorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntryPatientInfo.setBackground(new java.awt.Color(204, 204, 204));
        penEntryPatientInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryPatientInfo.setClosable(true);
        penEntryPatientInfo.setMaximizable(true);
        penEntryPatientInfo.setResizable(true);
        penEntryPatientInfo.setTitle("Entry Patient Info");
        penEntryPatientInfo.setToolTipText("Entry Patient Info");
        penEntryPatientInfo.setVisible(true);
        penEntryPatientInfo.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryPatientInfoInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryPatientInfo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryPatientInfoLayout = new javax.swing.GroupLayout(subPenOfEntryPatientInfo);
        subPenOfEntryPatientInfo.setLayout(subPenOfEntryPatientInfoLayout);
        subPenOfEntryPatientInfoLayout.setHorizontalGroup(
            subPenOfEntryPatientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryPatientInfoLayout.setVerticalGroup(
            subPenOfEntryPatientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryPatientInfoLayout = new javax.swing.GroupLayout(penEntryPatientInfo.getContentPane());
        penEntryPatientInfo.getContentPane().setLayout(penEntryPatientInfoLayout);
        penEntryPatientInfoLayout.setHorizontalGroup(
            penEntryPatientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryPatientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryPatientInfoLayout.setVerticalGroup(
            penEntryPatientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryPatientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntrySeviceInfo.setBackground(new java.awt.Color(204, 204, 204));
        penEntrySeviceInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntrySeviceInfo.setClosable(true);
        penEntrySeviceInfo.setMaximizable(true);
        penEntrySeviceInfo.setResizable(true);
        penEntrySeviceInfo.setTitle("Entry Service Info");
        penEntrySeviceInfo.setToolTipText("Entry Service Info");
        penEntrySeviceInfo.setVisible(true);
        penEntrySeviceInfo.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntrySeviceInfoInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryServiceInfo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryServiceInfoLayout = new javax.swing.GroupLayout(subPenOfEntryServiceInfo);
        subPenOfEntryServiceInfo.setLayout(subPenOfEntryServiceInfoLayout);
        subPenOfEntryServiceInfoLayout.setHorizontalGroup(
            subPenOfEntryServiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryServiceInfoLayout.setVerticalGroup(
            subPenOfEntryServiceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntrySeviceInfoLayout = new javax.swing.GroupLayout(penEntrySeviceInfo.getContentPane());
        penEntrySeviceInfo.getContentPane().setLayout(penEntrySeviceInfoLayout);
        penEntrySeviceInfoLayout.setHorizontalGroup(
            penEntrySeviceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryServiceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntrySeviceInfoLayout.setVerticalGroup(
            penEntrySeviceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryServiceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntryRoomInfo.setBackground(new java.awt.Color(204, 204, 204));
        penEntryRoomInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryRoomInfo.setClosable(true);
        penEntryRoomInfo.setMaximizable(true);
        penEntryRoomInfo.setTitle("Entry Room Info");
        penEntryRoomInfo.setToolTipText("Entry Service Info");
        penEntryRoomInfo.setVisible(true);
        penEntryRoomInfo.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryRoomInfoInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryRoomInfo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryRoomInfoLayout = new javax.swing.GroupLayout(subPenOfEntryRoomInfo);
        subPenOfEntryRoomInfo.setLayout(subPenOfEntryRoomInfoLayout);
        subPenOfEntryRoomInfoLayout.setHorizontalGroup(
            subPenOfEntryRoomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryRoomInfoLayout.setVerticalGroup(
            subPenOfEntryRoomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryRoomInfoLayout = new javax.swing.GroupLayout(penEntryRoomInfo.getContentPane());
        penEntryRoomInfo.getContentPane().setLayout(penEntryRoomInfoLayout);
        penEntryRoomInfoLayout.setHorizontalGroup(
            penEntryRoomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryRoomInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryRoomInfoLayout.setVerticalGroup(
            penEntryRoomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryRoomInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntryDoctorAppointment.setBackground(new java.awt.Color(204, 204, 204));
        penEntryDoctorAppointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryDoctorAppointment.setClosable(true);
        penEntryDoctorAppointment.setMaximizable(true);
        penEntryDoctorAppointment.setResizable(true);
        penEntryDoctorAppointment.setTitle("Entry Doctor Appointment");
        penEntryDoctorAppointment.setToolTipText("Entry Doctor Appointment");
        penEntryDoctorAppointment.setVisible(true);
        penEntryDoctorAppointment.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryDoctorAppointmentInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryDoctorAppointment.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryDoctorAppointmentLayout = new javax.swing.GroupLayout(subPenOfEntryDoctorAppointment);
        subPenOfEntryDoctorAppointment.setLayout(subPenOfEntryDoctorAppointmentLayout);
        subPenOfEntryDoctorAppointmentLayout.setHorizontalGroup(
            subPenOfEntryDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryDoctorAppointmentLayout.setVerticalGroup(
            subPenOfEntryDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryDoctorAppointmentLayout = new javax.swing.GroupLayout(penEntryDoctorAppointment.getContentPane());
        penEntryDoctorAppointment.getContentPane().setLayout(penEntryDoctorAppointmentLayout);
        penEntryDoctorAppointmentLayout.setHorizontalGroup(
            penEntryDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryDoctorAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryDoctorAppointmentLayout.setVerticalGroup(
            penEntryDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryDoctorAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntryRoomBooking.setBackground(new java.awt.Color(204, 204, 204));
        penEntryRoomBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryRoomBooking.setClosable(true);
        penEntryRoomBooking.setMaximizable(true);
        penEntryRoomBooking.setResizable(true);
        penEntryRoomBooking.setTitle("Entry Room Booking");
        penEntryRoomBooking.setToolTipText("Entry Room Booking");
        penEntryRoomBooking.setVisible(true);
        penEntryRoomBooking.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryRoomBookingInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryRoomBooking.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryRoomBookingLayout = new javax.swing.GroupLayout(subPenOfEntryRoomBooking);
        subPenOfEntryRoomBooking.setLayout(subPenOfEntryRoomBookingLayout);
        subPenOfEntryRoomBookingLayout.setHorizontalGroup(
            subPenOfEntryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryRoomBookingLayout.setVerticalGroup(
            subPenOfEntryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryRoomBookingLayout = new javax.swing.GroupLayout(penEntryRoomBooking.getContentPane());
        penEntryRoomBooking.getContentPane().setLayout(penEntryRoomBookingLayout);
        penEntryRoomBookingLayout.setHorizontalGroup(
            penEntryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryRoomBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryRoomBookingLayout.setVerticalGroup(
            penEntryRoomBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryRoomBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntryPatientAdmmisson.setBackground(new java.awt.Color(204, 204, 204));
        penEntryPatientAdmmisson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryPatientAdmmisson.setClosable(true);
        penEntryPatientAdmmisson.setMaximizable(true);
        penEntryPatientAdmmisson.setResizable(true);
        penEntryPatientAdmmisson.setTitle("Entry Patient Admission");
        penEntryPatientAdmmisson.setToolTipText("Entry Patient Admission");
        penEntryPatientAdmmisson.setVisible(true);
        penEntryPatientAdmmisson.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryPatientAdmmissonInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfEntryPatientAdmmisson.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfEntryPatientAdmmissonLayout = new javax.swing.GroupLayout(subPenOfEntryPatientAdmmisson);
        subPenOfEntryPatientAdmmisson.setLayout(subPenOfEntryPatientAdmmissonLayout);
        subPenOfEntryPatientAdmmissonLayout.setHorizontalGroup(
            subPenOfEntryPatientAdmmissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryPatientAdmmissonLayout.setVerticalGroup(
            subPenOfEntryPatientAdmmissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryPatientAdmmissonLayout = new javax.swing.GroupLayout(penEntryPatientAdmmisson.getContentPane());
        penEntryPatientAdmmisson.getContentPane().setLayout(penEntryPatientAdmmissonLayout);
        penEntryPatientAdmmissonLayout.setHorizontalGroup(
            penEntryPatientAdmmissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryPatientAdmmisson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryPatientAdmmissonLayout.setVerticalGroup(
            penEntryPatientAdmmissonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryPatientAdmmisson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penShowDoctorAppointment.setBackground(new java.awt.Color(204, 204, 204));
        penShowDoctorAppointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penShowDoctorAppointment.setClosable(true);
        penShowDoctorAppointment.setMaximizable(true);
        penShowDoctorAppointment.setResizable(true);
        penShowDoctorAppointment.setTitle("Entry Doctor Appointment");
        penShowDoctorAppointment.setToolTipText("Entry Doctor Appointment");
        penShowDoctorAppointment.setVisible(true);
        penShowDoctorAppointment.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penShowDoctorAppointmentInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        subPenOfShowDoctorAppointment.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout subPenOfShowDoctorAppointmentLayout = new javax.swing.GroupLayout(subPenOfShowDoctorAppointment);
        subPenOfShowDoctorAppointment.setLayout(subPenOfShowDoctorAppointmentLayout);
        subPenOfShowDoctorAppointmentLayout.setHorizontalGroup(
            subPenOfShowDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfShowDoctorAppointmentLayout.setVerticalGroup(
            subPenOfShowDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penShowDoctorAppointmentLayout = new javax.swing.GroupLayout(penShowDoctorAppointment.getContentPane());
        penShowDoctorAppointment.getContentPane().setLayout(penShowDoctorAppointmentLayout);
        penShowDoctorAppointmentLayout.setHorizontalGroup(
            penShowDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfShowDoctorAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penShowDoctorAppointmentLayout.setVerticalGroup(
            penShowDoctorAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfShowDoctorAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(10, 10));
        setName("MainFrame"); // NOI18N
        setSize(new java.awt.Dimension(900, 800));

        mainPen.setBackground(new java.awt.Color(255, 255, 224));

        lblShowCompany.setFont(new java.awt.Font("Lucida Calligraphy", 1, 50)); // NOI18N
        lblShowCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowCompany.setText("Hospital Management System");
        lblShowCompany.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize()
        );

        javax.swing.GroupLayout mainPenLayout = new javax.swing.GroupLayout(mainPen);
        mainPen.setLayout(mainPenLayout);
        mainPenLayout.setHorizontalGroup(
            mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShowCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        mainPenLayout.setVerticalGroup(
            mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPenLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblShowCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(257, 257, 257))
        );

        lblShowReord.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord.setText("Record 1/1");
        lblShowReord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblShowReord2.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord2.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord2.setText(" ");
        lblShowReord2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblShowReord3.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord3.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord3.setText(" < Server IP: 192.168.1.210 >");
        lblShowReord3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblShowReord4.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord4.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord4.setText(" ");
        lblShowReord4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblShowReord5.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord5.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord5.setText(" ");
        lblShowReord5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblCopyRightTeg.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        lblCopyRightTeg.setForeground(new java.awt.Color(255, 0, 51));
        lblCopyRightTeg.setText("@copyright: 2022 Versity Project");

        mainMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainMenuBar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mainMenuBar.setPreferredSize(new java.awt.Dimension(56, 30));

        menuEntry.setText("| Entry");
        menuEntry.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        menuEntry.setMargin(new java.awt.Insets(0, 0, 0, 15));

        manuItemEntryAdvanceAmount.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemEntryAdvanceAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemEntryAdvanceAmount.setText("Entry Doctor Information");
        manuItemEntryAdvanceAmount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemEntryAdvanceAmount.setBorderPainted(true);
        manuItemEntryAdvanceAmount.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemEntryAdvanceAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemEntryAdvanceAmountActionPerformed(evt);
            }
        });
        menuEntry.add(manuItemEntryAdvanceAmount);

        manuItemSubmitPanddingBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemSubmitPanddingBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemSubmitPanddingBill.setText("Entry Patient Information");
        manuItemSubmitPanddingBill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemSubmitPanddingBill.setBorderPainted(true);
        manuItemSubmitPanddingBill.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemSubmitPanddingBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemSubmitPanddingBillActionPerformed(evt);
            }
        });
        menuEntry.add(manuItemSubmitPanddingBill);

        manuItemIncomeAndCost.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost.setText("Entry Medical Service");
        manuItemIncomeAndCost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost.setBorderPainted(true);
        manuItemIncomeAndCost.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCostActionPerformed(evt);
            }
        });
        menuEntry.add(manuItemIncomeAndCost);

        manuItemIncomeAndCost3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost3.setText("Room Information Entry");
        manuItemIncomeAndCost3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost3.setBorderPainted(true);
        manuItemIncomeAndCost3.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCost3ActionPerformed(evt);
            }
        });
        menuEntry.add(manuItemIncomeAndCost3);

        mainMenuBar.add(menuEntry);

        menuEntry2.setText("| Process");
        menuEntry2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        menuEntry2.setMargin(new java.awt.Insets(0, 0, 0, 15));

        manuItemEntryAdvanceAmount2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemEntryAdvanceAmount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemEntryAdvanceAmount2.setText("Doctor Appointment");
        manuItemEntryAdvanceAmount2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemEntryAdvanceAmount2.setBorderPainted(true);
        manuItemEntryAdvanceAmount2.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemEntryAdvanceAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemEntryAdvanceAmount2ActionPerformed(evt);
            }
        });
        menuEntry2.add(manuItemEntryAdvanceAmount2);

        manuItemIncomeAndCost5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost5.setText("Patient Admission");
        manuItemIncomeAndCost5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost5.setBorderPainted(true);
        manuItemIncomeAndCost5.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCost5ActionPerformed(evt);
            }
        });
        menuEntry2.add(manuItemIncomeAndCost5);

        manuItemIncomeAndCost4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost4.setText("Room Booking Entry");
        manuItemIncomeAndCost4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost4.setBorderPainted(true);
        manuItemIncomeAndCost4.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCost4ActionPerformed(evt);
            }
        });
        menuEntry2.add(manuItemIncomeAndCost4);

        mainMenuBar.add(menuEntry2);

        menuEntry1.setText("| View");
        menuEntry1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        menuEntry1.setMargin(new java.awt.Insets(0, 0, 0, 15));

        manuItemIncomeAndCost6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost6.setText("View Doctor Appointment");
        manuItemIncomeAndCost6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost6.setBorderPainted(true);
        manuItemIncomeAndCost6.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCost6ActionPerformed(evt);
            }
        });
        menuEntry1.add(manuItemIncomeAndCost6);

        manuItemIncomeAndCost8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost8.setText("View Room Booking");
        manuItemIncomeAndCost8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost8.setBorderPainted(true);
        manuItemIncomeAndCost8.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCost8ActionPerformed(evt);
            }
        });
        menuEntry1.add(manuItemIncomeAndCost8);

        manuItemIncomeAndCost9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemIncomeAndCost9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemIncomeAndCost9.setText("View Patient Admission");
        manuItemIncomeAndCost9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        manuItemIncomeAndCost9.setBorderPainted(true);
        manuItemIncomeAndCost9.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemIncomeAndCost9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemIncomeAndCost9ActionPerformed(evt);
            }
        });
        menuEntry1.add(manuItemIncomeAndCost9);

        mainMenuBar.add(menuEntry1);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblShowReord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowReord2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowReord4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowReord5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowReord3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCopyRightTeg))
            .addComponent(mainPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowReord)
                    .addComponent(lblShowReord2)
                    .addComponent(lblShowReord3)
                    .addComponent(lblShowReord4)
                    .addComponent(lblShowReord5)
                    .addComponent(lblCopyRightTeg)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manuItemEntryAdvanceAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemEntryAdvanceAmountActionPerformed
        // TODO add your handling code here:
        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInEntryAdvanceAmount();
        penEntryDoctorInfo.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryDoctorInfo.setVisible(true);
        mainPen.add(penEntryDoctorInfo, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemEntryAdvanceAmountActionPerformed

    private void manuItemSubmitPanddingBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemSubmitPanddingBillActionPerformed

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInEntryPatientInfo();
        penEntryPatientInfo.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryPatientInfo.setVisible(true);
        mainPen.add(penEntryPatientInfo, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();
    }//GEN-LAST:event_manuItemSubmitPanddingBillActionPerformed

    private void manuItemIncomeAndCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCostActionPerformed

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInEntryServiceInfo();
        penEntrySeviceInfo.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntrySeviceInfo.setVisible(true);
        mainPen.add(penEntrySeviceInfo, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemIncomeAndCostActionPerformed

    private void manuItemIncomeAndCost3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCost3ActionPerformed
        // TODO add your handling code here:

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInEntryRoomInfo();
        penEntryRoomInfo.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryRoomInfo.setVisible(true);
        mainPen.add(penEntryRoomInfo, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemIncomeAndCost3ActionPerformed

    private void manuItemIncomeAndCost4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCost4ActionPerformed
        // TODO add your handling code here:

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        sql:

        addPenInRoomBooking();
        penEntryRoomBooking.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryRoomBooking.setVisible(true);
        mainPen.add(penEntryRoomBooking, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemIncomeAndCost4ActionPerformed

    private void manuItemIncomeAndCost5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCost5ActionPerformed
        // TODO add your handling code here:
        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInEntryPatitentAddmission();
        penEntryPatientAdmmisson.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryPatientAdmmisson.setVisible(true);
        mainPen.add(penEntryPatientAdmmisson, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemIncomeAndCost5ActionPerformed

    private void penEntryDoctorInfoInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryDoctorInfoInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penEntryDoctorInfo);
        showLableInMainWindow();
    }//GEN-LAST:event_penEntryDoctorInfoInternalFrameClosed

    private void manuItemIncomeAndCost6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCost6ActionPerformed
        // TODO add your handling code here:

        /*hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }
        
        
        addPenInShowDoctorAppointment();
        penShowDoctorAppointment.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penShowDoctorAppointment.setVisible(true);
        mainPen.add(penShowDoctorAppointment, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();*/
        new ShowAllDoctorAppointment().setVisible(true);
    }//GEN-LAST:event_manuItemIncomeAndCost6ActionPerformed

    private void manuItemIncomeAndCost8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCost8ActionPerformed
        // TODO add your handling code here:

        new ShowAllRoomBookingList().setVisible(true);
    }//GEN-LAST:event_manuItemIncomeAndCost8ActionPerformed

    private void manuItemIncomeAndCost9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemIncomeAndCost9ActionPerformed
        // TODO add your handling code here:
        new ShowAllPatientAdmission().setVisible(true);
    }//GEN-LAST:event_manuItemIncomeAndCost9ActionPerformed

    private void penEntryPatientInfoInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryPatientInfoInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penEntryPatientInfo);
        showLableInMainWindow();
    }//GEN-LAST:event_penEntryPatientInfoInternalFrameClosed

    private void penEntrySeviceInfoInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntrySeviceInfoInternalFrameClosed
        // TODO add your handling code here
        mainPen.remove(penEntrySeviceInfo);
        showLableInMainWindow();
    }//GEN-LAST:event_penEntrySeviceInfoInternalFrameClosed

    private void manuItemEntryAdvanceAmount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemEntryAdvanceAmount2ActionPerformed
        // TODO add your handling code here:

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = componentSize, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInDoctorAppointment();
        penEntryDoctorAppointment.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryDoctorAppointment.setVisible(true);
        mainPen.add(penEntryDoctorAppointment, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemEntryAdvanceAmount2ActionPerformed

    private void penEntryRoomInfoInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryRoomInfoInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penEntryRoomInfo);
        showLableInMainWindow();
    }//GEN-LAST:event_penEntryRoomInfoInternalFrameClosed

    private void penEntryDoctorAppointmentInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryDoctorAppointmentInternalFrameClosed
        mainPen.remove(penEntryDoctorAppointment);
        showLableInMainWindow();

        // TODO add your handling code here:
    }//GEN-LAST:event_penEntryDoctorAppointmentInternalFrameClosed

    private void penEntryRoomBookingInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryRoomBookingInternalFrameClosed
        mainPen.remove(penEntryRoomBooking);
        showLableInMainWindow();
        // TODO add your handling code here:
    }//GEN-LAST:event_penEntryRoomBookingInternalFrameClosed

    private void penEntryPatientAdmmissonInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryPatientAdmmissonInternalFrameClosed
        mainPen.remove(penEntryPatientAdmmisson);
        showLableInMainWindow();
        // TODO add your handling code here:
    }//GEN-LAST:event_penEntryPatientAdmmissonInternalFrameClosed

    private void penShowDoctorAppointmentInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penShowDoctorAppointmentInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_penShowDoctorAppointmentInternalFrameClosed

    private void addPenInEntryAdvanceAmount() {
        subPenOfEntryDoctorInfo.setLayout(new GridLayout(1, 1));
        subPenOfEntryDoctorInfo.removeAll();
        DoctorInformation doctorInfo = new DoctorInformation();
        subPenOfEntryDoctorInfo.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryDoctorInfo.add(doctorInfo);
        subPenOfEntryDoctorInfo.revalidate();
        subPenOfEntryDoctorInfo.repaint();
    }

    private void addPenInEntryPatientInfo() {
        subPenOfEntryPatientInfo.setLayout(new GridLayout(1, 1));
        subPenOfEntryPatientInfo.removeAll();
        PatientInformation information = new PatientInformation();
        subPenOfEntryPatientInfo.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryPatientInfo.add(information);
        subPenOfEntryPatientInfo.revalidate();
        subPenOfEntryPatientInfo.repaint();
    }

    private void addPenInEntryServiceInfo() {
        subPenOfEntryServiceInfo.setLayout(new GridLayout(1, 1));
        subPenOfEntryServiceInfo.removeAll();
        MedicalServiceInformation information = new MedicalServiceInformation();
        subPenOfEntryServiceInfo.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryServiceInfo.add(information);
        subPenOfEntryServiceInfo.revalidate();
        subPenOfEntryServiceInfo.repaint();
    }

    private void addPenInEntryRoomInfo() {
        subPenOfEntryRoomInfo.setLayout(new GridLayout(1, 1));
        subPenOfEntryRoomInfo.removeAll();
        RoomInfromation information = new RoomInfromation();
        subPenOfEntryRoomInfo.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryRoomInfo.add(information);
        subPenOfEntryRoomInfo.revalidate();
        subPenOfEntryRoomInfo.repaint();
    }

    private void addPenInDoctorAppointment() {
        subPenOfEntryDoctorAppointment.setLayout(new GridLayout(1, 1));
        subPenOfEntryDoctorAppointment.removeAll();
        DoctorAppointment information = new DoctorAppointment();
        subPenOfEntryDoctorAppointment.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryDoctorAppointment.add(information);
        subPenOfEntryDoctorAppointment.revalidate();
        subPenOfEntryDoctorAppointment.repaint();
    }

    private void addPenInRoomBooking() {
        subPenOfEntryRoomBooking.setLayout(new GridLayout(1, 1));
        subPenOfEntryRoomBooking.removeAll();
        RoomBooking information = new RoomBooking();
        subPenOfEntryRoomBooking.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryRoomBooking.add(information);
        subPenOfEntryRoomBooking.revalidate();
        subPenOfEntryRoomBooking.repaint();
    }

    private void addPenInEntryPatitentAddmission() {
        subPenOfEntryPatientAdmmisson.setLayout(new GridLayout(1, 1));
        subPenOfEntryPatientAdmmisson.removeAll();
        PatientAdmission admission = new PatientAdmission();
        subPenOfEntryPatientAdmmisson.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfEntryPatientAdmmisson.add(admission);
        subPenOfEntryPatientAdmmisson.revalidate();
        subPenOfEntryPatientAdmmisson.repaint();
    }

    private void addPenInShowDoctorAppointment() {
        subPenOfShowDoctorAppointment.setLayout(new GridLayout(1, 1));
        subPenOfShowDoctorAppointment.removeAll();
        ShowAllDoctorAppointment admission = new ShowAllDoctorAppointment();
        subPenOfShowDoctorAppointment.setBorder(new EmptyBorder(subPenTopBorder, subPenLeftBorder, subPenBottomBorder, subPenRightBorder));
        subPenOfShowDoctorAppointment.add(admission);
        subPenOfShowDoctorAppointment.revalidate();
        subPenOfShowDoctorAppointment.repaint();
    }

    private void hideLableInMainWindow() {

        lblShowCompany.setVisible(false);
        lblCopyRightTeg.setVisible(false);
    }

    private void showLableInMainWindow() {
        if (mainPen.getComponentCount() == componentSize) {
            lblShowCompany.setVisible(true);
            lblCopyRightTeg.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWorkingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCopyRightTeg;
    private javax.swing.JLabel lblShowCompany;
    private javax.swing.JLabel lblShowReord;
    private javax.swing.JLabel lblShowReord2;
    private javax.swing.JLabel lblShowReord3;
    private javax.swing.JLabel lblShowReord4;
    private javax.swing.JLabel lblShowReord5;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPen;
    private javax.swing.JMenuItem manuItemEntryAdvanceAmount;
    private javax.swing.JMenuItem manuItemEntryAdvanceAmount2;
    private javax.swing.JMenuItem manuItemIncomeAndCost;
    private javax.swing.JMenuItem manuItemIncomeAndCost3;
    private javax.swing.JMenuItem manuItemIncomeAndCost4;
    private javax.swing.JMenuItem manuItemIncomeAndCost5;
    private javax.swing.JMenuItem manuItemIncomeAndCost6;
    private javax.swing.JMenuItem manuItemIncomeAndCost8;
    private javax.swing.JMenuItem manuItemIncomeAndCost9;
    private javax.swing.JMenuItem manuItemSubmitPanddingBill;
    private javax.swing.JMenu menuEntry;
    private javax.swing.JMenu menuEntry1;
    private javax.swing.JMenu menuEntry2;
    private javax.swing.JInternalFrame penEntryDoctorAppointment;
    private javax.swing.JInternalFrame penEntryDoctorInfo;
    private javax.swing.JInternalFrame penEntryPatientAdmmisson;
    private javax.swing.JInternalFrame penEntryPatientInfo;
    private javax.swing.JInternalFrame penEntryRoomBooking;
    private javax.swing.JInternalFrame penEntryRoomInfo;
    private javax.swing.JInternalFrame penEntrySeviceInfo;
    private javax.swing.JInternalFrame penShowDoctorAppointment;
    private javax.swing.JPanel subPenOfEntryDoctorAppointment;
    private javax.swing.JPanel subPenOfEntryDoctorInfo;
    private javax.swing.JPanel subPenOfEntryPatientAdmmisson;
    private javax.swing.JPanel subPenOfEntryPatientInfo;
    private javax.swing.JPanel subPenOfEntryRoomBooking;
    private javax.swing.JPanel subPenOfEntryRoomInfo;
    private javax.swing.JPanel subPenOfEntryServiceInfo;
    private javax.swing.JPanel subPenOfShowDoctorAppointment;
    // End of variables declaration//GEN-END:variables
}
