INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
1, 'Production', 'Inspection', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
2, 'Production', 'Eyelet', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
3, 'Production', 'Crown', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
4, 'Production', 'PanNel', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
5, 'Production', 'Assembly', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
7, 'Production', 'Cutting', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
8, 'Production', 'Adjuster', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
9, 'Production', 'Pannel', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
10, 'Production', 'Visor', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
12, 'Administration', 'General Staff', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
13, 'Administration', 'Office Staff', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
14, 'Production', 'Crown 04 + Assembly 04', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO TB_SECTION_INFO ( SECID, DEPARTTMENTNM, SECTIONNM, SECTIONADDRESS, SECTIONPHONE,
WEBADDRESS, PROCESSBY, PROCESSDATE, SEC_NAME_BANGLA, MANPOWER ) VALUES ( 
16, 'Administration', 'Security', NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
commit;
 
