package reportgenerator.view.subwindow;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import reportgenerator.corefunction.IOFunction;
import reportgenerator.corefunction.WriteChallanReport;
import reportgenerator.dao.ChallanReportComponent;

/**
 *
 * @author Anik
 */
public class ChalanReportGenerator extends javax.swing.JPanel {

    private String savingLoc;
    //private String savingLoc = "\\\\192.168.1.210\\monthly_online_bill_and_quotation\\";
    private String configComapnyListUrl;
    private String configPendingBillList;
    private String recentFileLoc = "";
    private String recentReqQutBillFileLoc = "";
    private String monthlyBillType = "MONTHLY-BILL";
    private String reqBillType = "SOFT-REQ-BILL";
    private String monthlyBillSavingTeg = "Monthly-Bill";
    private String reqBillSavingTeg = "Chalan";
    private String openFolderUrl = "";
    private int vatAmount = 0;
    private int totalAmount = 0;
    private String currentDate="";

    private List<String> companyAndAddressList = new ArrayList<>();

    private int keyTypeChecker = 0;

    /**
     * Creates new form ReportGenerate
     */
    public ChalanReportGenerator(String savingLoc, String configCompanyLoc, String configPanddingLoc) {
        this.savingLoc = savingLoc;
        this.configComapnyListUrl = configCompanyLoc;
        this.configPendingBillList = configPanddingLoc;
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("ddMMyyyy-HHmmss");
        currentDate = simpleDateFormat.format(new Date());
        
        initComponents();
        showCompanyNameInComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboMonth = new javax.swing.JComboBox<>();
        comboYear = new javax.swing.JComboBox<>();
        comboCompany = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        txtItemRow1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAmountRow1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtItemRow2 = new javax.swing.JTextField();
        txtAmountRow2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItemRow3 = new javax.swing.JTextField();
        txtAmountRow3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtItemRow4 = new javax.swing.JTextField();
        txtAmountRow4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtItemRow5 = new javax.swing.JTextField();
        txtAmountRow5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtItemRow6 = new javax.swing.JTextField();
        txtAmountRow6 = new javax.swing.JTextField();
        txtItemRow7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAmountRow7 = new javax.swing.JTextField();
        txtItemRow8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAmountRow8 = new javax.swing.JTextField();
        txtItemRow9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAmountRow9 = new javax.swing.JTextField();
        txtItemRow10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAmountRow10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtItemRow11 = new javax.swing.JTextField();
        txtAmountRow11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtItemRow12 = new javax.swing.JTextField();
        txtAmountRow12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtItemRow13 = new javax.swing.JTextField();
        txtAmountRow13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtItemRow14 = new javax.swing.JTextField();
        txtAmountRow14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtItemRow15 = new javax.swing.JTextField();
        txtAmountRow15 = new javax.swing.JTextField();
        txtRemarks1 = new javax.swing.JTextField();
        txtRemarks2 = new javax.swing.JTextField();
        txtRemarks3 = new javax.swing.JTextField();
        txtRemarks4 = new javax.swing.JTextField();
        txtRemarks5 = new javax.swing.JTextField();
        txtRemarks6 = new javax.swing.JTextField();
        txtRemarks7 = new javax.swing.JTextField();
        txtRemarks8 = new javax.swing.JTextField();
        txtRemarks9 = new javax.swing.JTextField();
        txtRemarks10 = new javax.swing.JTextField();
        txtRemarks11 = new javax.swing.JTextField();
        txtRemarks12 = new javax.swing.JTextField();
        txtRemarks13 = new javax.swing.JTextField();
        txtRemarks14 = new javax.swing.JTextField();
        txtRemarks15 = new javax.swing.JTextField();
        comboQtyType1 = new javax.swing.JComboBox<>();
        comboQtyType2 = new javax.swing.JComboBox<>();
        comboQtyType3 = new javax.swing.JComboBox<>();
        comboQtyType4 = new javax.swing.JComboBox<>();
        comboQtyType5 = new javax.swing.JComboBox<>();
        comboQtyType6 = new javax.swing.JComboBox<>();
        comboQtyType7 = new javax.swing.JComboBox<>();
        comboQtyType8 = new javax.swing.JComboBox<>();
        comboQtyType9 = new javax.swing.JComboBox<>();
        comboQtyType10 = new javax.swing.JComboBox<>();
        comboQtyType11 = new javax.swing.JComboBox<>();
        comboQtyType12 = new javax.swing.JComboBox<>();
        comboQtyType13 = new javax.swing.JComboBox<>();
        comboQtyType14 = new javax.swing.JComboBox<>();
        comboQtyType15 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        btnMakeChalan = new javax.swing.JButton();
        txtAttention = new javax.swing.JTextField();
        txtDeliveryPerson = new javax.swing.JTextField();
        txtChalanNo = new javax.swing.JTextField();
        txtWorkOrderDate = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 224));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 224));

        comboMonth.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comboMonth.setToolTipText("");
        comboMonth.setEnabled(false);

        comboYear.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        comboYear.setToolTipText("");
        comboYear.setEnabled(false);

        comboCompany.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        comboCompany.setMaximumRowCount(100);
        comboCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company Name" }));
        comboCompany.setToolTipText("");

        txtDate.setBackground(new java.awt.Color(0, 255, 255));
        txtDate.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateKeyPressed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 224));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 224));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        txtItemRow1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("01");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAmountRow1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow1.setText("0");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel2.setText("02");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow2.setText("0");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel3.setText("03");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow3.setText("0");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel4.setText("04");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow4.setText("0");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel5.setText("05");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow5.setText("0");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel6.setText("06");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow6.setText("0");

        txtItemRow7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel7.setText("07");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAmountRow7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow7.setText("0");

        txtItemRow8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel8.setText("08");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAmountRow8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow8.setText("0");
        txtAmountRow8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountRow8ActionPerformed(evt);
            }
        });

        txtItemRow9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel10.setText("09");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAmountRow9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow9.setText("0");

        txtItemRow10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel11.setText("10");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAmountRow10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow10.setText("0");

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel12.setText("11");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow11.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow11.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow11.setText("0");

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel13.setText("12");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow12.setText("0");

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel14.setText("13");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow13.setText("0");

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel15.setText("14");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow14.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow14.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow14.setText("0");

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel16.setText("15");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtItemRow15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtAmountRow15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountRow15.setText("0");

        txtRemarks1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks11.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks14.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtRemarks15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        comboQtyType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtItemRow14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(txtItemRow13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRow15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAmountRow14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(txtAmountRow13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountRow15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboQtyType1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboQtyType14, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboQtyType15, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtRemarks5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRemarks3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRemarks2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRemarks4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtRemarks15))
                    .addComponent(txtRemarks1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRemarks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRemarks3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRemarks5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtItemRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtItemRow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtItemRow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtItemRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItemRow5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtItemRow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtItemRow7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtItemRow8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtItemRow9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmountRow9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRemarks9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboQtyType9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtItemRow10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRow10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQtyType10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtItemRow11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRow11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQtyType11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtItemRow12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRow12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQtyType12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtItemRow13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRow13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQtyType13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtItemRow14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRow14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQtyType14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtItemRow15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRow15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemarks15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQtyType15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("S/L |                 Item Dtls                              ||               Qty                   |              |     Remarks     ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOpen.setBackground(new java.awt.Color(255, 255, 255));
        btnOpen.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnDownload.setBackground(new java.awt.Color(255, 255, 255));
        btnDownload.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/down-arrow.png"))); // NOI18N
        btnDownload.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnDownload.setContentAreaFilled(false);
        btnDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnMakeChalan.setBackground(new java.awt.Color(255, 255, 255));
        btnMakeChalan.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnMakeChalan.setText("Make Chalan");
        btnMakeChalan.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        btnMakeChalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeChalanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMakeChalan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMakeChalan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        txtAttention.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAttention.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Attention", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtAttention.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAttentionKeyPressed(evt);
            }
        });

        txtDeliveryPerson.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDeliveryPerson.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Delivery Person", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtDeliveryPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeliveryPersonKeyPressed(evt);
            }
        });

        txtChalanNo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtChalanNo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Challan No", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtChalanNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChalanNoKeyPressed(evt);
            }
        });

        txtWorkOrderDate.setBackground(new java.awt.Color(0, 255, 255));
        txtWorkOrderDate.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtWorkOrderDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Work Order Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtWorkOrderDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWorkOrderDateFocusGained(evt);
            }
        });
        txtWorkOrderDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWorkOrderDateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtWorkOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAttention))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(comboMonth, 0, 218, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeliveryPerson)
                            .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtChalanNo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChalanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(comboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAttention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeliveryPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        // TODO add your handling code here:
        txtDate.setText("");
        keyTypeChecker = 0;
    }//GEN-LAST:event_txtDateFocusGained

    private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed
        // TODO add your handling code here:

        if (keyTypeChecker == 8) {
            String date = txtDate.getText();
            String day = date.substring(0, 2);
            String month = date.substring(2, 4);
            String year = date.substring(4, 8);
            System.out.println(day + "/" + month + "/" + year);
            txtDate.setText(day + "/" + month + "/" + year);
            txtWorkOrderDate.requestFocus();
        }
        keyTypeChecker++;
        
    }//GEN-LAST:event_txtDateKeyPressed

    private void txtAmountRow8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountRow8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountRow8ActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        try {
            if (!recentFileLoc.isEmpty()) {
                File file = new File(recentFileLoc);
                Desktop desktop = Desktop.getDesktop();
                desktop.open(file);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    ":: Error-04 :: ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        try {
            if (!recentFileLoc.isEmpty()) {

                // copy file in local D:/ drive by File channel
                File srcFile = new File(recentFileLoc);
                File distFile = new File("D:\\" + srcFile.getName());
                FileChannel srcChannel = new FileInputStream(srcFile).getChannel();
                FileChannel distChannel = new FileOutputStream(distFile).getChannel();

                distChannel.transferFrom(srcChannel, 0, srcChannel.size());
                srcChannel.close();
                distChannel.close();

                JOptionPane.showMessageDialog(null, "File Download in " + distFile.getAbsolutePath(),
                        ":: Download :: ", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    ":: Error-13 :: ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3MouseEntered

    private void txtWorkOrderDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWorkOrderDateFocusGained
        // TODO add your handling code here:
        txtWorkOrderDate.setText("");
        keyTypeChecker = 0;
    }//GEN-LAST:event_txtWorkOrderDateFocusGained

    private void txtWorkOrderDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWorkOrderDateKeyPressed
        // TODO add your handling code here:

        if (keyTypeChecker == 8) {
            String date = txtWorkOrderDate.getText();
            String day = date.substring(0, 2);
            String month = date.substring(2, 4);
            String year = date.substring(4, 8);
            System.out.println(day + "/" + month + "/" + year);
            txtWorkOrderDate.setText(day + "/" + month + "/" + year);
            txtAttention.requestFocus();
        }
        keyTypeChecker++;
    }//GEN-LAST:event_txtWorkOrderDateKeyPressed

    private void btnMakeChalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeChalanActionPerformed
        // TODO add your handling code here:
        
        if ((txtDate.getText().length() > 9) 
                && (txtWorkOrderDate.getText().length()>9) 
                && (comboCompany.getSelectedIndex() > 0)) 
        {
            // split company name and address
            // replace string , replace space to '-' charecter
            String parts[] = comboCompany.getSelectedItem().toString().split("-");
            parts[1] = parts[1].replace(' ', '-');
            parts[1] = parts[1].replace(".", "");
            String url = savingLoc + reqBillSavingTeg + "\\" + parts[1] + "\\";
            openFolderUrl = url;
            
            url += parts[1] + "-Chalan-Report-" + currentDate + ".pdf";
            recentFileLoc = url;

            File selectedFile = new File(url);
            
            if (new WriteChallanReport().writeChallanReportInPdfFile(setReqDataInArray(), selectedFile)) {
                System.out.println("Qutation make --> ");
                JOptionPane.showMessageDialog(null, "Challan Is Generated.",
                        ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Challan Isn't Generated.",
                        ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Select Company, Month, Year, Date",
                    ":: Please Select :: ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnMakeChalanActionPerformed

    private void txtAttentionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAttentionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDeliveryPerson.requestFocus();
        }
    }//GEN-LAST:event_txtAttentionKeyPressed

    private void txtDeliveryPersonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeliveryPersonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnMakeChalan.requestFocus();
        }
    }//GEN-LAST:event_txtDeliveryPersonKeyPressed

    private void txtChalanNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChalanNoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDate.requestFocus();
        }
    }//GEN-LAST:event_txtChalanNoKeyPressed

    private void showCompanyNameInComboBox() {
        companyAndAddressList = new IOFunction().getCompanyNameAndAddress(configComapnyListUrl);

        int i = 0;
        while (i != companyAndAddressList.size()) {
            comboCompany.addItem(i + "-" + companyAndAddressList.get(i));
            i += 2;
        }
    }

    private List<ChallanReportComponent> setReqDataInArray() {

        List<ChallanReportComponent> components = new ArrayList<>();
        // Devided company name and address, using '-' charcater
        // using split() function
        String parts[] = comboCompany.getSelectedItem().toString().split("-");
        String amount = " ";

        // Add information in list
        ChallanReportComponent component1 = new ChallanReportComponent();
        component1.setDeliveryDate(txtDate.getText());
        component1.setWorkOrderDate(txtWorkOrderDate.getText());
        component1.setCompanyName(parts[1]);
        component1.setAddress(companyAndAddressList.get(Integer.parseInt(parts[0]) + 1));
        component1.setChallanNo(txtChalanNo.getText());
        component1.setAttention(txtAttention.getText());
        component1.setDeliveryPerson(txtDeliveryPerson.getText());
        component1.setProductName(txtItemRow1.getText());
        component1.setQuantity(Integer.valueOf(txtAmountRow1.getText()));
        component1.setRemarks(txtRemarks1.getText());
        component1.setUnit(comboQtyType1.getSelectedItem().toString());
        components.add(component1);

        ChallanReportComponent component2 = new ChallanReportComponent();
        component2.setProductName(txtItemRow2.getText());
        component2.setQuantity(Integer.valueOf(txtAmountRow2.getText()));
        component2.setRemarks(txtRemarks2.getText());
        component2.setUnit(comboQtyType2.getSelectedItem().toString());
        components.add(component2);

        ChallanReportComponent component3 = new ChallanReportComponent();
        component3.setProductName(txtItemRow3.getText());
        component3.setQuantity(Integer.valueOf(txtAmountRow3.getText()));
        component3.setRemarks(txtRemarks3.getText());
        component3.setUnit(comboQtyType3.getSelectedItem().toString());
        components.add(component3);


        ChallanReportComponent component4 = new ChallanReportComponent();
        component4.setProductName(txtItemRow4.getText());
        component4.setQuantity(Integer.valueOf(txtAmountRow4.getText()));
        component4.setRemarks(txtRemarks4.getText());
        component4.setUnit(comboQtyType4.getSelectedItem().toString());
        components.add(component4);


        ChallanReportComponent component5 = new ChallanReportComponent();
        component5.setProductName(txtItemRow5.getText());
        component5.setQuantity(Integer.valueOf(txtAmountRow5.getText()));
        component5.setRemarks(txtRemarks5.getText());
        component5.setUnit(comboQtyType5.getSelectedItem().toString());
        components.add(component5);

        ChallanReportComponent component6 = new ChallanReportComponent();
        component6.setProductName(txtItemRow6.getText());
        component6.setQuantity(Integer.valueOf(txtAmountRow6.getText()));
        component6.setRemarks(txtRemarks6.getText());
        component6.setUnit(comboQtyType6.getSelectedItem().toString());
        components.add(component6);

        ChallanReportComponent component7 = new ChallanReportComponent();
        component7.setProductName(txtItemRow7.getText());
        component7.setQuantity(Integer.valueOf(txtAmountRow7.getText()));
        component7.setRemarks(txtRemarks7.getText());
        component7.setUnit(comboQtyType7.getSelectedItem().toString());
        components.add(component7);

        ChallanReportComponent component8 = new ChallanReportComponent();
        component8.setProductName(txtItemRow8.getText());
        component8.setQuantity(Integer.valueOf(txtAmountRow8.getText()));
        component8.setRemarks(txtRemarks8.getText());
        component8.setUnit(comboQtyType8.getSelectedItem().toString());
        components.add(component8);

        ChallanReportComponent component9 = new ChallanReportComponent();
        component9.setProductName(txtItemRow9.getText());
        component9.setQuantity(Integer.valueOf(txtAmountRow9.getText()));
        component9.setRemarks(txtRemarks9.getText());
        component9.setUnit(comboQtyType9.getSelectedItem().toString());
        components.add(component9);

        ChallanReportComponent component10 = new ChallanReportComponent();
        component10.setProductName(txtItemRow10.getText());
        component10.setQuantity(Integer.valueOf(txtAmountRow10.getText()));
        component10.setRemarks(txtRemarks10.getText());
        component10.setUnit(comboQtyType10.getSelectedItem().toString());
        components.add(component10);

        ChallanReportComponent component11 = new ChallanReportComponent();
        component11.setProductName(txtItemRow11.getText());
        component11.setQuantity(Integer.valueOf(txtAmountRow11.getText()));
        component11.setRemarks(txtRemarks11.getText());
        component11.setUnit(comboQtyType11.getSelectedItem().toString());
        components.add(component11);

        ChallanReportComponent component12 = new ChallanReportComponent();
        component12.setProductName(txtItemRow12.getText());
        component12.setQuantity(Integer.valueOf(txtAmountRow12.getText()));
        component12.setRemarks(txtRemarks12.getText());
        component12.setUnit(comboQtyType12.getSelectedItem().toString());
        components.add(component12);
        
        ChallanReportComponent component13 = new ChallanReportComponent();
        component13.setProductName(txtItemRow13.getText());
        component13.setQuantity(Integer.valueOf(txtAmountRow13.getText()));
        component13.setRemarks(txtRemarks13.getText());
        component13.setUnit(comboQtyType13.getSelectedItem().toString());
        components.add(component13);
        
        
        ChallanReportComponent component14 = new ChallanReportComponent();
        component14.setProductName(txtItemRow14.getText());
        component14.setQuantity(Integer.valueOf(txtAmountRow14.getText()));
        component14.setRemarks(txtRemarks14.getText());
        component14.setUnit(comboQtyType14.getSelectedItem().toString());
        components.add(component14);
        
        return components;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnMakeChalan;
    private javax.swing.JButton btnOpen;
    private javax.swing.JComboBox<String> comboCompany;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboQtyType1;
    private javax.swing.JComboBox<String> comboQtyType10;
    private javax.swing.JComboBox<String> comboQtyType11;
    private javax.swing.JComboBox<String> comboQtyType12;
    private javax.swing.JComboBox<String> comboQtyType13;
    private javax.swing.JComboBox<String> comboQtyType14;
    private javax.swing.JComboBox<String> comboQtyType15;
    private javax.swing.JComboBox<String> comboQtyType2;
    private javax.swing.JComboBox<String> comboQtyType3;
    private javax.swing.JComboBox<String> comboQtyType4;
    private javax.swing.JComboBox<String> comboQtyType5;
    private javax.swing.JComboBox<String> comboQtyType6;
    private javax.swing.JComboBox<String> comboQtyType7;
    private javax.swing.JComboBox<String> comboQtyType8;
    private javax.swing.JComboBox<String> comboQtyType9;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtAmountRow1;
    private javax.swing.JTextField txtAmountRow10;
    private javax.swing.JTextField txtAmountRow11;
    private javax.swing.JTextField txtAmountRow12;
    private javax.swing.JTextField txtAmountRow13;
    private javax.swing.JTextField txtAmountRow14;
    private javax.swing.JTextField txtAmountRow15;
    private javax.swing.JTextField txtAmountRow2;
    private javax.swing.JTextField txtAmountRow3;
    private javax.swing.JTextField txtAmountRow4;
    private javax.swing.JTextField txtAmountRow5;
    private javax.swing.JTextField txtAmountRow6;
    private javax.swing.JTextField txtAmountRow7;
    private javax.swing.JTextField txtAmountRow8;
    private javax.swing.JTextField txtAmountRow9;
    private javax.swing.JTextField txtAttention;
    private javax.swing.JTextField txtChalanNo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeliveryPerson;
    private javax.swing.JTextField txtItemRow1;
    private javax.swing.JTextField txtItemRow10;
    private javax.swing.JTextField txtItemRow11;
    private javax.swing.JTextField txtItemRow12;
    private javax.swing.JTextField txtItemRow13;
    private javax.swing.JTextField txtItemRow14;
    private javax.swing.JTextField txtItemRow15;
    private javax.swing.JTextField txtItemRow2;
    private javax.swing.JTextField txtItemRow3;
    private javax.swing.JTextField txtItemRow4;
    private javax.swing.JTextField txtItemRow5;
    private javax.swing.JTextField txtItemRow6;
    private javax.swing.JTextField txtItemRow7;
    private javax.swing.JTextField txtItemRow8;
    private javax.swing.JTextField txtItemRow9;
    private javax.swing.JTextField txtRemarks1;
    private javax.swing.JTextField txtRemarks10;
    private javax.swing.JTextField txtRemarks11;
    private javax.swing.JTextField txtRemarks12;
    private javax.swing.JTextField txtRemarks13;
    private javax.swing.JTextField txtRemarks14;
    private javax.swing.JTextField txtRemarks15;
    private javax.swing.JTextField txtRemarks2;
    private javax.swing.JTextField txtRemarks3;
    private javax.swing.JTextField txtRemarks4;
    private javax.swing.JTextField txtRemarks5;
    private javax.swing.JTextField txtRemarks6;
    private javax.swing.JTextField txtRemarks7;
    private javax.swing.JTextField txtRemarks8;
    private javax.swing.JTextField txtRemarks9;
    private javax.swing.JTextField txtWorkOrderDate;
    // End of variables declaration//GEN-END:variables
}
