/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportgenerator.view.subwindow;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import reportgenerator.corefunction.IOFunction;
import reportgenerator.corefunction.WriteHardwareQut;
import reportgenerator.corefunction.WriteHardwareQutBill;
import reportgenerator.corefunction.WriteHardwareQutBillHardCopy;
import reportgenerator.dao.EntrySubmitedBillDao;
import reportgenerator.dao.HardwareQutComponent;
import reportgenerator.service.EntrySubmitedBillService;

/**
 *
 * @author Anik
 */
public class ReportGenerateHardware extends javax.swing.JPanel {

    private JTextField brandName[];
    private JTextField modelName[];
    private JTextField originName[];
    private JTextField warranty[];
    private JTextField faceCapacity[];
    private JTextField fingerCapacity[];
    private JTextField cardCapacity[];
    private JTextField eventLog[];
    private JTextField comWay[];
    private JTextField deviceQty[];
    private JTextField deviceUnitPrice[];
    private String date;
    private String companyName;
    private String companyAddress;
    private String savingLoc;
    private String configComapnyListUrl;
    private String configPendingBillList;
    private float totalAmounts = 0;
    private String recentFileLocation;
    private int keyTypeChecker = 0;
    private String hardwareBillType = "HARD-REQ-BILL";
    private String openFolderUrl = "";
    private String reqBillSavingTeg = "Requirment-Bill-&-Quotation";
    private float vatAmount = 0;
    private String currentDate="";
    
    List<HardwareQutComponent> listOfHarwareQut = new ArrayList<>();
    private List<String> companyAndAddressList = new ArrayList<>();

    /**
     * Creates new form ReportGenerateHardware
     */
    public ReportGenerateHardware(String savingLoc, String configCompanyLoc, String configPanddingLoc) {
        initComponents();

        this.savingLoc = savingLoc;
        this.configComapnyListUrl = configCompanyLoc;
        this.configPendingBillList = configPanddingLoc;
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("ddMMyyyy-HHmmss");
        currentDate = simpleDateFormat.format(new Date());
        
        initComponents();
        showListOfPenel();
        showCompanyNameInComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanShowList = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDtls9 = new javax.swing.JTextField();
        txtDtls1 = new javax.swing.JTextField();
        txtDtls3 = new javax.swing.JTextField();
        txtDtls2 = new javax.swing.JTextField();
        txtDtls5 = new javax.swing.JTextField();
        txtDtls8 = new javax.swing.JTextField();
        txtDtls10 = new javax.swing.JTextField();
        txtDtls6 = new javax.swing.JTextField();
        txtDtls4 = new javax.swing.JTextField();
        txtDtls7 = new javax.swing.JTextField();
        txtMoreDtls3 = new javax.swing.JTextField();
        txtMoreDtls1 = new javax.swing.JTextField();
        txtMoreDtls6 = new javax.swing.JTextField();
        txtMoreDtls7 = new javax.swing.JTextField();
        txtMoreDtls8 = new javax.swing.JTextField();
        txtMoreDtls2 = new javax.swing.JTextField();
        txtMoreDtls5 = new javax.swing.JTextField();
        txtMoreDtls9 = new javax.swing.JTextField();
        txtMoreDtls4 = new javax.swing.JTextField();
        txtMoreDtls10 = new javax.swing.JTextField();
        txtQty1 = new javax.swing.JTextField();
        txtQty5 = new javax.swing.JTextField();
        txtQty10 = new javax.swing.JTextField();
        txtQty4 = new javax.swing.JTextField();
        txtQty6 = new javax.swing.JTextField();
        txtQty9 = new javax.swing.JTextField();
        txtQty2 = new javax.swing.JTextField();
        txtQty3 = new javax.swing.JTextField();
        txtQty7 = new javax.swing.JTextField();
        txtQty8 = new javax.swing.JTextField();
        txtUnitPrice5 = new javax.swing.JTextField();
        txtUnitPrice8 = new javax.swing.JTextField();
        txtUnitPrice6 = new javax.swing.JTextField();
        txtUnitPrice10 = new javax.swing.JTextField();
        txtUnitPrice2 = new javax.swing.JTextField();
        txtUnitPrice1 = new javax.swing.JTextField();
        txtUnitPrice9 = new javax.swing.JTextField();
        txtUnitPrice3 = new javax.swing.JTextField();
        txtUnitPrice7 = new javax.swing.JTextField();
        txtUnitPrice4 = new javax.swing.JTextField();
        lblTotalAmount = new javax.swing.JLabel();
        checkBoxHardwareQutHardCopy = new javax.swing.JCheckBox();
        comboMonth = new javax.swing.JComboBox<>();
        comboCompany = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        comboYear = new javax.swing.JComboBox<>();
        txtVAT = new javax.swing.JTextField();
        btnMakeHardwareQut = new javax.swing.JButton();
        txtHardwareBillNo = new javax.swing.JTextField();
        btnMakeHardwareQutBill = new javax.swing.JButton();
        txtAmountInWord = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        comboQtyType1 = new javax.swing.JComboBox<>();
        comboQtyType4 = new javax.swing.JComboBox<>();
        comboQtyType7 = new javax.swing.JComboBox<>();
        btnOpenFile = new javax.swing.JButton();
        comboQtyType6 = new javax.swing.JComboBox<>();
        comboQtyType5 = new javax.swing.JComboBox<>();
        comboQtyType9 = new javax.swing.JComboBox<>();
        btnDownloadFile = new javax.swing.JButton();
        comboQtyType2 = new javax.swing.JComboBox<>();
        comboQtyType3 = new javax.swing.JComboBox<>();
        comboQtyType8 = new javax.swing.JComboBox<>();
        comboQtyType10 = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 224));

        jPanShowList.setBackground(new java.awt.Color(255, 255, 224));

        javax.swing.GroupLayout jPanShowListLayout = new javax.swing.GroupLayout(jPanShowList);
        jPanShowList.setLayout(jPanShowListLayout);
        jPanShowListLayout.setHorizontalGroup(
            jPanShowListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        jPanShowListLayout.setVerticalGroup(
            jPanShowListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanShowList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Write Divice Info", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 224));

        jPanel1.setBackground(new java.awt.Color(255, 255, 224));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 224));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Dtls");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Dtls2");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Qty");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Unit Price");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDtls9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtQty1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty1.setText("0");

        txtQty5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty5.setText("0");

        txtQty10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty10.setText("0");

        txtQty4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty4.setText("0");

        txtQty6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty6.setText("0");

        txtQty9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty9.setText("0");

        txtQty2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty2.setText("0");

        txtQty3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty3.setText("0");

        txtQty7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty7.setText("0");

        txtQty8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty8.setText("0");

        txtUnitPrice5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice5.setText("0");

        txtUnitPrice8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice8.setText("0");

        txtUnitPrice6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice6.setText("0");

        txtUnitPrice10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice10.setText("0");

        txtUnitPrice2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice2.setText("0");

        txtUnitPrice1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice1.setText("0");

        txtUnitPrice9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice9.setText("0");

        txtUnitPrice3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice3.setText("0");

        txtUnitPrice7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice7.setText("0");

        txtUnitPrice4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice4.setText("0");

        lblTotalAmount.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalAmount.setText("0");
        lblTotalAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        lblTotalAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTotalAmountMouseEntered(evt);
            }
        });

        checkBoxHardwareQutHardCopy.setBackground(new java.awt.Color(255, 255, 224));
        checkBoxHardwareQutHardCopy.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        checkBoxHardwareQutHardCopy.setText("Hard Copy");
        checkBoxHardwareQutHardCopy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        checkBoxHardwareQutHardCopy.setBorderPainted(true);

        comboMonth.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comboMonth.setToolTipText("");

        comboCompany.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        comboCompany.setMaximumRowCount(100);
        comboCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company Name" }));
        comboCompany.setToolTipText("");

        txtDate.setBackground(new java.awt.Color(0, 255, 255));
        txtDate.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateKeyPressed(evt);
            }
        });

        comboYear.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        comboYear.setToolTipText("");

        txtVAT.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtVAT.setText("0");
        txtVAT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total VAT %", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(txtDtls10, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(txtDtls9)
                            .addComponent(txtDtls7)
                            .addComponent(txtDtls6)
                            .addComponent(txtDtls2)
                            .addComponent(txtDtls3)
                            .addComponent(txtDtls1)
                            .addComponent(txtDtls8)
                            .addComponent(txtDtls4)
                            .addComponent(txtDtls5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(txtMoreDtls8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMoreDtls1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMoreDtls2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMoreDtls3)
                            .addComponent(txtMoreDtls5)
                            .addComponent(txtMoreDtls6)
                            .addComponent(txtMoreDtls9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMoreDtls10)
                            .addComponent(txtMoreDtls7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMoreDtls4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCompany, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboYear, 0, 172, Short.MAX_VALUE)
                            .addComponent(txtDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVAT)
                            .addComponent(checkBoxHardwareQutHardCopy, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQty2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtQty5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty8)
                            .addComponent(txtQty4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtQty7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtQty10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtQty1))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUnitPrice2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice8)
                                    .addComponent(txtUnitPrice4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtUnitPrice3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnitPrice1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDtls1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDtls7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMoreDtls7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtQty7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUnitPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtls3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQty4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnitPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMoreDtls4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDtls4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtls5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtls6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVAT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDate)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(comboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkBoxHardwareQutHardCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        btnMakeHardwareQut.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnMakeHardwareQut.setText("Generate Qutitoin");
        btnMakeHardwareQut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeHardwareQutActionPerformed(evt);
            }
        });

        txtHardwareBillNo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtHardwareBillNo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bill Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        btnMakeHardwareQutBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnMakeHardwareQutBill.setText("Generate Qutitoin Bill");
        btnMakeHardwareQutBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeHardwareQutBillActionPerformed(evt);
            }
        });

        txtAmountInWord.setBackground(new java.awt.Color(0, 255, 255));
        txtAmountInWord.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtAmountInWord.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Amount In Word", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N
        txtAmountInWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountInWordFocusGained(evt);
            }
        });
        txtAmountInWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAmountInWordMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHardwareBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmountInWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMakeHardwareQut, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMakeHardwareQutBill, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHardwareBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAmountInWord, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnMakeHardwareQut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnMakeHardwareQutBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboQtyType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        btnOpenFile.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnOpenFile.setText("Open File");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        comboQtyType6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        btnDownloadFile.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnDownloadFile.setText("Download");
        btnDownloadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadFileActionPerformed(evt);
            }
        });

        comboQtyType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboQtyType1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownloadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(comboQtyType1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboQtyType10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDownloadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Write Other Item", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblTotalAmountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalAmountMouseEntered
        // TODO add your handling code here:
        totalAmounts = 0;
        setData();
        lblTotalAmount.setText(String.valueOf(totalAmounts));
    }//GEN-LAST:event_lblTotalAmountMouseEntered

    private void btnMakeHardwareQutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeHardwareQutActionPerformed
        // TODO add your handling code here:
        showData(setData());

        setDateAndCompany();

        String comName = companyName.replace(' ', '-');
        comName = comName.replace(".", "");

        WriteHardwareQut writeQut = new WriteHardwareQut();
        writeQut.setAmountInWord(txtAmountInWord.getText());
        String url = savingLoc + reqBillSavingTeg + "\\" + comName + "\\";
        openFolderUrl = url;
        recentFileLocation = url + comName + "-Req-Hardware-Qtnt-" + currentDate + ".pdf";
        File selectedFile = new File(recentFileLocation);

        if (writeQut.writeHardwareQutInPdfFile(setData(), selectedFile)) {
            System.out.println("Qutation make --> ");
            JOptionPane.showMessageDialog(null, "Qutation Is Generated.",
                    ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Qutation Isn't Generated.",
                    ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMakeHardwareQutActionPerformed

    private void btnMakeHardwareQutBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeHardwareQutBillActionPerformed
        // TODO add your handling code here:
        EntrySubmitedBillDao billDao = new EntrySubmitedBillDao();
        setDateAndCompany();

        String comName = companyName.replace(' ', '-');
        comName = comName.replace(".", "");

        // set bill information for update
        billDao.setBillDate(txtDate.getText());
        billDao.setBillNumber(txtHardwareBillNo.getText());
        billDao.setCompanyName(companyName);
        billDao.setAmount(Float.valueOf(lblTotalAmount.getText()));
        billDao.setBillType(hardwareBillType);

        String url = savingLoc + reqBillSavingTeg + "\\" + comName + "\\";
        openFolderUrl = url;

        if (!checkBoxHardwareQutHardCopy.isSelected()) {

            WriteHardwareQutBill writeQutBill = new WriteHardwareQutBill();
            writeQutBill.setAmountInWord(txtAmountInWord.getText());
            recentFileLocation = url + comName + "-Req-Hardware-Qtnt-Bill-soft-copy" + currentDate + ".pdf";
            File selectedFile = new File(recentFileLocation);

            if (writeQutBill.writeHardwareQutBillInPdfFile(setData(), selectedFile)) {
                // update data in database
                if (new EntrySubmitedBillService().checkBillNumberAllreadyEntry(txtHardwareBillNo.getText(), companyName)) {
                    new EntrySubmitedBillService().saveData(billDao);
                }
                JOptionPane.showMessageDialog(null, "Qutation Is Generated.",
                        ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Qutation Isn't Generated.",
                        ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            WriteHardwareQutBillHardCopy writeHardQutBill = new WriteHardwareQutBillHardCopy();
            writeHardQutBill.setAmountInWord(txtAmountInWord.getText());
            recentFileLocation = url + comName + "-Req-Hardware-Qtnt-Bill-hard-copy" + System.currentTimeMillis() + ".pdf";
            File selectedFile = new File(recentFileLocation);

            if (writeHardQutBill.writeHardwareQutBillInPdfFile(setData(), selectedFile)) {
                // update data in database
                if (new EntrySubmitedBillService().checkBillNumberAllreadyEntry(txtHardwareBillNo.getText(), companyName)) {
                    new EntrySubmitedBillService().saveData(billDao);
                }
                JOptionPane.showMessageDialog(null, "Qutation Is Generated.",
                        ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Qutation Isn't Generated.",
                        ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnMakeHardwareQutBillActionPerformed

    private void txtAmountInWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmountInWordMouseEntered
        // TODO add your handling code here:
        totalAmounts = 0;
        setData();
        lblTotalAmount.setText(String.valueOf(totalAmounts));
    }//GEN-LAST:event_txtAmountInWordMouseEntered

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
        try {
            if (!recentFileLocation.isEmpty()) {
                File file = new File(recentFileLocation);
                Desktop desktop = Desktop.getDesktop();
                desktop.open(file);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    ":: Error-04 :: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnDownloadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadFileActionPerformed
        // TODO add your handling code here:
        try {
            if (!savingLoc.isEmpty()) {
//                File file = new File(openFolderUrl);
//                Desktop desktop = Desktop.getDesktop();
//                desktop.open(file);

                File srcFile = new File(recentFileLocation);
                File distFile = new File("D:\\" + srcFile.getName());
                FileChannel srcChannel = new FileInputStream(srcFile).getChannel();
                FileChannel distChannel = new FileOutputStream(distFile).getChannel();

                distChannel.transferFrom(srcChannel, 0, srcChannel.size());
                srcChannel.close();
                distChannel.close();

                JOptionPane.showMessageDialog(null, "File Download in " + distFile.getAbsolutePath(),
                        ":: Download :: ", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    ":: Error-13 :: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDownloadFileActionPerformed

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        // TODO add your handling code here:
        txtDate.setText("");
        keyTypeChecker = 0;
    }//GEN-LAST:event_txtDateFocusGained

    private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed
        // TODO add your handling code here:

        if (keyTypeChecker == 8) {
            String date = txtDate.getText();
            String day = date.substring(0, 2);
            String month = date.substring(2, 4);
            String year = date.substring(4, 8);

            System.out.println(day + "/" + month + "/" + year);
            txtDate.setText(day + "/" + month + "/" + year);
            txtAmountInWord.requestFocus();
        }
        keyTypeChecker++;
    }//GEN-LAST:event_txtDateKeyPressed

    private void txtAmountInWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountInWordFocusGained
        // TODO add your handling code here:
        try {
            float amount = totalAmounts;
            vatAmount = (amount * (Integer.valueOf(txtVAT.getText())) / 100);
            amount += vatAmount;
            lblTotalAmount.setText(String.valueOf(amount));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    ":: Error-Adding Amount :: ", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_txtAmountInWordFocusGained

    private void showListOfPenel() {
        JPanel pan[] = new JPanel[10];
        jPanShowList.setLayout(new GridLayout(0, 1, 20, 20));

        brandName = new JTextField[5];
        modelName = new JTextField[5];
        originName = new JTextField[5];
        warranty = new JTextField[5];
        faceCapacity = new JTextField[5];
        fingerCapacity = new JTextField[5];
        cardCapacity = new JTextField[5];
        eventLog = new JTextField[5];
        comWay = new JTextField[5];
        deviceQty = new JTextField[5];
        deviceUnitPrice = new JTextField[5];

        for (int i = 0; i < 5; i++) {

            pan[i] = new JPanel();
            pan[i].setLayout(new GridLayout(1, 6, 5, 15));

            String label[] = {"Brand:", "Model:", "Origin:", "Warranty:", "Face Cap:", "Finger Cap:", "Card Cap:",
                "Event Log:", "Com way:", "Qty:", "Unit Price:"};

            brandName[i] = new JTextField();
            brandName[i].setBorder(new TitledBorder(label[0]));
            modelName[i] = new JTextField();
            modelName[i].setBorder(new TitledBorder(label[1]));
            originName[i] = new JTextField();
            originName[i].setBorder(new TitledBorder(label[2]));
            warranty[i] = new JTextField("0");
            warranty[i].setBorder(new TitledBorder(label[3]));
            faceCapacity[i] = new JTextField("0");
            faceCapacity[i].setBorder(new TitledBorder(label[4]));
            fingerCapacity[i] = new JTextField("0");
            fingerCapacity[i].setBorder(new TitledBorder(label[5]));
            cardCapacity[i] = new JTextField("0");
            cardCapacity[i].setBorder(new TitledBorder(label[6]));
            eventLog[i] = new JTextField("0");
            eventLog[i].setBorder(new TitledBorder(label[7]));
            comWay[i] = new JTextField();
            comWay[i].setBorder(new TitledBorder(label[8]));
            deviceQty[i] = new JTextField("0");
            deviceQty[i].setBorder(new TitledBorder(label[9]));
            deviceUnitPrice[i] = new JTextField("0");
            deviceUnitPrice[i].setBorder(new TitledBorder(label[10]));

            pan[i].add(brandName[i]);
            pan[i].add(modelName[i]);
            pan[i].add(originName[i]);
            pan[i].add(warranty[i]);
            pan[i].add(faceCapacity[i]);
            pan[i].add(fingerCapacity[i]);
            pan[i].add(cardCapacity[i]);
            pan[i].add(eventLog[i]);
            pan[i].add(comWay[i]);
            pan[i].add(deviceQty[i]);
            pan[i].add(deviceUnitPrice[i]);
            pan[i].revalidate();
            pan[i].repaint();
            pan[i].setBackground(Color.WHITE);

            jPanShowList.add(pan[i]);
            jPanShowList.revalidate();
            jPanShowList.repaint();
        }

    }

    private List<HardwareQutComponent> setData() {

        List<HardwareQutComponent> listOfComponent = new ArrayList<>();
        String tempStr = "";

        int i = 0;
        while (i < 5) {

            if (!modelName[i].getText().isEmpty()) {
                HardwareQutComponent component = new HardwareQutComponent();
                // set data in list
                component.setDate(date);
                component.setCompanyName(companyName);
                component.setBillNo(txtHardwareBillNo.getText());
                component.setAddress(companyAddress);
                component.setBrand(brandName[i].getText());
                component.setModel(modelName[i].getText());
                component.setOrigin(originName[i].getText());
                component.setWarranty(Integer.parseInt(warranty[i].getText()));
                component.setFaceCapacity(Integer.parseInt(faceCapacity[i].getText()));
                component.setFingerCapacity(Integer.parseInt(fingerCapacity[i].getText()));
                component.setCardCapacity(Integer.parseInt(cardCapacity[i].getText()));
                component.setEventLog(Integer.parseInt(eventLog[i].getText()));
                component.setCommunicationWay(comWay[i].getText());
                int dvcQty = Integer.parseInt(deviceQty[i].getText());
                component.setDeviceQty(dvcQty);
                float dvcUnitPrice = Float.valueOf(deviceUnitPrice[i].getText());
                component.setDeviceUnitPrice(dvcUnitPrice);
                float dvcTotalAmount = dvcUnitPrice * dvcQty;
                component.setDeviceTotalPrice(dvcTotalAmount);
                component.setVatPrcn(Integer.valueOf(txtVAT.getText()));
                component.setVatAmount(vatAmount);
                // set total amount in label
                totalAmounts += dvcTotalAmount;

                listOfComponent.add(component);
            }
            i++;
        }

        if (!txtDtls1.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls1.getText());
            component.setDtls02(txtMoreDtls1.getText());
            int qty = Integer.parseInt(txtQty1.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice1.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType1.getSelectedItem().toString());
            component.setVatPrcn(Integer.valueOf(txtVAT.getText()));
            component.setVatAmount(vatAmount);
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls2.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls2.getText());
            component.setDtls02(txtMoreDtls2.getText());
            int qty = Integer.parseInt(txtQty2.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice2.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType2.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls3.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls3.getText());
            component.setDtls02(txtMoreDtls3.getText());
            int qty = Integer.parseInt(txtQty3.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice3.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType3.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls4.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls4.getText());
            component.setDtls02(txtMoreDtls4.getText());
            int qty = Integer.parseInt(txtQty4.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice4.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType4.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls5.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls5.getText());
            component.setDtls02(txtMoreDtls5.getText());
            int qty = Integer.parseInt(txtQty5.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice5.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType5.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls6.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls6.getText());
            component.setDtls02(txtMoreDtls6.getText());
            int qty = Integer.parseInt(txtQty6.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice6.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType6.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls7.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls7.getText());
            component.setDtls02(txtMoreDtls7.getText());
            int qty = Integer.parseInt(txtQty7.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice7.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType7.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls8.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls8.getText());
            component.setDtls02(txtMoreDtls8.getText());
            int qty = Integer.parseInt(txtQty8.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice8.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType8.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls9.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls9.getText());
            component.setDtls02(txtMoreDtls9.getText());
            int qty = Integer.parseInt(txtQty9.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice9.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType9.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        if (!txtDtls10.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls10.getText());
            component.setDtls02(txtMoreDtls10.getText());
            int qty = Integer.parseInt(txtQty10.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice10.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType10.getSelectedItem().toString());
            totalAmounts += totalPrice;
            listOfComponent.add(component);
        }

        return listOfComponent;
    }

    private void showCompanyNameInComboBox() {
        companyAndAddressList = new IOFunction().getCompanyNameAndAddress(configComapnyListUrl);

        int i = 0;
        while (i != companyAndAddressList.size()) {
            comboCompany.addItem(i + "-" + companyAndAddressList.get(i));
            i += 2;
        }
    }

    private void setDateAndCompany() {
        this.date = txtDate.getText();
        String parts[] = comboCompany.getSelectedItem().toString().split("-");

        this.companyName = parts[1];
        this.companyAddress = companyAndAddressList.get(Integer.parseInt(parts[0]) + 1);
    }

    private void showData(List<HardwareQutComponent> list) {
        System.out.println(list.size());

        for (int i = 0; i < list.size(); i++) {
            try {
                if (!list.get(i).getBrand().isEmpty()) {
                    System.out.println(list.get(i).getBrand());
                    System.out.println(list.get(i).getModel());
                    System.out.println(list.get(i).getFingerCapacity());
                    System.out.println(list.get(i).getCardCapacity());
                    System.out.println(list.get(i).getCommunicationWay());
                } else if (!list.get(i).getDtls01().isEmpty()) {
                    System.out.println(list.get(i).getDtls01());
                    System.out.println(list.get(i).getDtls02());
                    System.out.println(list.get(i).getTotalPrice());
                } else {
                    break;
                }
            } catch (NullPointerException e) {
                e.printStackTrace();
            }
            System.out.println("===========================================");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownloadFile;
    private javax.swing.JButton btnMakeHardwareQut;
    private javax.swing.JButton btnMakeHardwareQutBill;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JCheckBox checkBoxHardwareQutHardCopy;
    private javax.swing.JComboBox<String> comboCompany;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboQtyType1;
    private javax.swing.JComboBox<String> comboQtyType10;
    private javax.swing.JComboBox<String> comboQtyType2;
    private javax.swing.JComboBox<String> comboQtyType3;
    private javax.swing.JComboBox<String> comboQtyType4;
    private javax.swing.JComboBox<String> comboQtyType5;
    private javax.swing.JComboBox<String> comboQtyType6;
    private javax.swing.JComboBox<String> comboQtyType7;
    private javax.swing.JComboBox<String> comboQtyType8;
    private javax.swing.JComboBox<String> comboQtyType9;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanShowList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTextField txtAmountInWord;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDtls1;
    private javax.swing.JTextField txtDtls10;
    private javax.swing.JTextField txtDtls2;
    private javax.swing.JTextField txtDtls3;
    private javax.swing.JTextField txtDtls4;
    private javax.swing.JTextField txtDtls5;
    private javax.swing.JTextField txtDtls6;
    private javax.swing.JTextField txtDtls7;
    private javax.swing.JTextField txtDtls8;
    private javax.swing.JTextField txtDtls9;
    private javax.swing.JTextField txtHardwareBillNo;
    private javax.swing.JTextField txtMoreDtls1;
    private javax.swing.JTextField txtMoreDtls10;
    private javax.swing.JTextField txtMoreDtls2;
    private javax.swing.JTextField txtMoreDtls3;
    private javax.swing.JTextField txtMoreDtls4;
    private javax.swing.JTextField txtMoreDtls5;
    private javax.swing.JTextField txtMoreDtls6;
    private javax.swing.JTextField txtMoreDtls7;
    private javax.swing.JTextField txtMoreDtls8;
    private javax.swing.JTextField txtMoreDtls9;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQty10;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtQty3;
    private javax.swing.JTextField txtQty4;
    private javax.swing.JTextField txtQty5;
    private javax.swing.JTextField txtQty6;
    private javax.swing.JTextField txtQty7;
    private javax.swing.JTextField txtQty8;
    private javax.swing.JTextField txtQty9;
    private javax.swing.JTextField txtUnitPrice1;
    private javax.swing.JTextField txtUnitPrice10;
    private javax.swing.JTextField txtUnitPrice2;
    private javax.swing.JTextField txtUnitPrice3;
    private javax.swing.JTextField txtUnitPrice4;
    private javax.swing.JTextField txtUnitPrice5;
    private javax.swing.JTextField txtUnitPrice6;
    private javax.swing.JTextField txtUnitPrice7;
    private javax.swing.JTextField txtUnitPrice8;
    private javax.swing.JTextField txtUnitPrice9;
    private javax.swing.JTextField txtVAT;
    // End of variables declaration//GEN-END:variables
}
