/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportgenerator.view.subwindow;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import reportgenerator.dbConnection.ConfigKeyList;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Anik
 */
public class SetupDatabaseInfo extends javax.swing.JPanel {

    private ConfigKeyList KEY_LIST = new ConfigKeyList();
    private String configUrl;

    /**
     * Creates new form SetupDatabaseInfo
     */
    public SetupDatabaseInfo(String url) {
        initComponents();
        
        configUrl = url;
        showInEntryPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupRuning = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtDatabasePassword = new javax.swing.JTextField();
        txtDatabaseName = new javax.swing.JTextField();
        txtDatabaseUserName = new javax.swing.JTextField();
        txtPortNumber = new javax.swing.JTextField();
        txtBaseUrl = new javax.swing.JTextField();
        txtHostName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblHostName2 = new javax.swing.JLabel();
        lblDatabaseUserName4 = new javax.swing.JLabel();
        lblDatabseName5 = new javax.swing.JLabel();
        lblHostName3 = new javax.swing.JLabel();
        lblDatabseName2 = new javax.swing.JLabel();
        lblDatabaseUserName5 = new javax.swing.JLabel();
        checkBoxRuning3 = new javax.swing.JCheckBox();
        lblDatabaseUserName2 = new javax.swing.JLabel();
        lblPort4 = new javax.swing.JLabel();
        checkBoxRuning4 = new javax.swing.JCheckBox();
        checkBoxRuning1 = new javax.swing.JCheckBox();
        lblPort5 = new javax.swing.JLabel();
        checkBoxRuning2 = new javax.swing.JCheckBox();
        lblPort3 = new javax.swing.JLabel();
        lblHostName1 = new javax.swing.JLabel();
        lblDatabseName1 = new javax.swing.JLabel();
        lblHostName4 = new javax.swing.JLabel();
        lblPort2 = new javax.swing.JLabel();
        lblPort1 = new javax.swing.JLabel();
        checkBoxRuning5 = new javax.swing.JCheckBox();
        lblDatabseName3 = new javax.swing.JLabel();
        lblDatabseName4 = new javax.swing.JLabel();
        lblDatabaseUserName1 = new javax.swing.JLabel();
        lblDatabaseUserName3 = new javax.swing.JLabel();
        lblHostName5 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDatabasePassword.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDatabasePassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Database Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        txtDatabaseName.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDatabaseName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Database Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        txtDatabaseUserName.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtDatabaseUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Database User Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        txtPortNumber.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtPortNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Port Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        txtBaseUrl.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtBaseUrl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Base Url Of Database", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        txtHostName.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtHostName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Host", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBaseUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatabaseUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHostName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(txtPortNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDatabasePassword)
                    .addComponent(txtDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaseUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatabaseUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatabasePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnSave.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 204, 153));

        lblHostName2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblHostName2.setText(" ");
        lblHostName2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabaseUserName4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabaseUserName4.setText(" ");
        lblDatabaseUserName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabseName5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabseName5.setText(" ");
        lblDatabseName5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHostName3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblHostName3.setText(" ");
        lblHostName3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabseName2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabseName2.setText(" ");
        lblDatabseName2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabaseUserName5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabaseUserName5.setText(" ");
        lblDatabaseUserName5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkBoxRuning3.setBackground(new java.awt.Color(255, 255, 0));
        btnGroupRuning.add(checkBoxRuning3);
        checkBoxRuning3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkBoxRuning3.setText("Runing");
        checkBoxRuning3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabaseUserName2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabaseUserName2.setText(" ");
        lblDatabaseUserName2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPort4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPort4.setText(" ");
        lblPort4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkBoxRuning4.setBackground(new java.awt.Color(255, 255, 0));
        btnGroupRuning.add(checkBoxRuning4);
        checkBoxRuning4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkBoxRuning4.setText("Runing");
        checkBoxRuning4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkBoxRuning1.setBackground(new java.awt.Color(255, 255, 0));
        btnGroupRuning.add(checkBoxRuning1);
        checkBoxRuning1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkBoxRuning1.setText("Runing");
        checkBoxRuning1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPort5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPort5.setText(" ");
        lblPort5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkBoxRuning2.setBackground(new java.awt.Color(255, 255, 0));
        btnGroupRuning.add(checkBoxRuning2);
        checkBoxRuning2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkBoxRuning2.setText("Runing");
        checkBoxRuning2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPort3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPort3.setText(" ");
        lblPort3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHostName1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblHostName1.setText(" ");
        lblHostName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabseName1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabseName1.setText(" ");
        lblDatabseName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHostName4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblHostName4.setText(" ");
        lblHostName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPort2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPort2.setText(" ");
        lblPort2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPort1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblPort1.setText(" ");
        lblPort1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkBoxRuning5.setBackground(new java.awt.Color(255, 255, 0));
        btnGroupRuning.add(checkBoxRuning5);
        checkBoxRuning5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkBoxRuning5.setText("Runing");
        checkBoxRuning5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabseName3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabseName3.setText(" ");
        lblDatabseName3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabseName4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabseName4.setText(" ");
        lblDatabseName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabaseUserName1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabaseUserName1.setText(" ");
        lblDatabaseUserName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatabaseUserName3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblDatabaseUserName3.setText(" ");
        lblDatabaseUserName3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHostName5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblHostName5.setText(" ");
        lblHostName5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHostName5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabseName5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabaseUserName5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxRuning5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHostName4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabseName4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabaseUserName4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxRuning4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHostName3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabseName3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabaseUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxRuning3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHostName1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabseName1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabaseUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxRuning1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHostName2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabseName2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatabaseUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxRuning2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHostName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabseName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabaseUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRuning1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHostName2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabseName2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabaseUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRuning2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHostName3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabseName3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabaseUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRuning3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHostName4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabseName4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabaseUserName4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRuning4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHostName5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabseName5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabaseUserName5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxRuning5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnEdit.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (saveSetupInformation()) {
            JOptionPane.showMessageDialog(
                    null, "Data Save In Setup File",
                    ":: Saved :: ", JOptionPane.INFORMATION_MESSAGE);
        }
        showSetupInformation();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private boolean saveSetupInformation() {

        try (OutputStream out = new FileOutputStream(configUrl)) {
            Properties properties = new Properties();

            properties.setProperty(KEY_LIST.KEY_DATABSE_NAME, txtDatabaseName.getText());
            properties.setProperty(KEY_LIST.KEY_ORACLE_BASE_URL, txtBaseUrl.getText());
            properties.setProperty(KEY_LIST.KEY_PORT_NUMBER, txtPortNumber.getText());
            properties.setProperty(KEY_LIST.KEY_SERVER_NAME, txtHostName.getText());
            properties.setProperty(KEY_LIST.KEY_USER_NAME, txtDatabaseUserName.getText());
            properties.setProperty(KEY_LIST.KEY_USER_PASSWORD, txtDatabasePassword.getText());
            
            properties.store(out, "Update-Database-Info");
            properties.clear();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    null, "Check File Exists? " + e.getMessage(),
                    ":: File Not Found :: ", JOptionPane.INFORMATION_MESSAGE);
        }
        return true;
    }

    private void showSetupInformation() {
        try (InputStream input = new java.io.FileInputStream(configUrl)) {
            Properties properties = new Properties();
            properties.load(input);
            lblHostName1.setText(properties.getProperty(KEY_LIST.KEY_SERVER_NAME));
            lblPort1.setText(properties.getProperty(KEY_LIST.KEY_PORT_NUMBER));
            lblDatabseName1.setText(properties.getProperty(KEY_LIST.KEY_DATABSE_NAME));
            lblDatabaseUserName1.setText(properties.getProperty(KEY_LIST.KEY_USER_NAME));

            properties.clear();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    null, "Check File Exists? " + e.getMessage(),
                    ":: File Not Found :: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void showInEntryPanel(){
        try (InputStream input = new java.io.FileInputStream(configUrl)) {
            Properties properties = new Properties();
            properties.load(input);
            
            txtBaseUrl.setText(properties.getProperty(KEY_LIST.KEY_ORACLE_BASE_URL));
            txtHostName.setText(properties.getProperty(KEY_LIST.KEY_SERVER_NAME));
            txtPortNumber.setText(properties.getProperty(KEY_LIST.KEY_PORT_NUMBER));
            txtDatabaseName.setText(properties.getProperty(KEY_LIST.KEY_DATABSE_NAME));
            txtDatabaseUserName.setText(properties.getProperty(KEY_LIST.KEY_USER_NAME));
            txtDatabasePassword.setText(properties.getProperty(KEY_LIST.KEY_USER_PASSWORD));
            properties.clear();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    null, "Check File Exists? " + e.getMessage(),
                    ":: File Not Found :: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGroupRuning;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkBoxRuning1;
    private javax.swing.JCheckBox checkBoxRuning2;
    private javax.swing.JCheckBox checkBoxRuning3;
    private javax.swing.JCheckBox checkBoxRuning4;
    private javax.swing.JCheckBox checkBoxRuning5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDatabaseUserName1;
    private javax.swing.JLabel lblDatabaseUserName2;
    private javax.swing.JLabel lblDatabaseUserName3;
    private javax.swing.JLabel lblDatabaseUserName4;
    private javax.swing.JLabel lblDatabaseUserName5;
    private javax.swing.JLabel lblDatabseName1;
    private javax.swing.JLabel lblDatabseName2;
    private javax.swing.JLabel lblDatabseName3;
    private javax.swing.JLabel lblDatabseName4;
    private javax.swing.JLabel lblDatabseName5;
    private javax.swing.JLabel lblHostName1;
    private javax.swing.JLabel lblHostName2;
    private javax.swing.JLabel lblHostName3;
    private javax.swing.JLabel lblHostName4;
    private javax.swing.JLabel lblHostName5;
    private javax.swing.JLabel lblPort1;
    private javax.swing.JLabel lblPort2;
    private javax.swing.JLabel lblPort3;
    private javax.swing.JLabel lblPort4;
    private javax.swing.JLabel lblPort5;
    private javax.swing.JTextField txtBaseUrl;
    private javax.swing.JTextField txtDatabaseName;
    private javax.swing.JTextField txtDatabasePassword;
    private javax.swing.JTextField txtDatabaseUserName;
    private javax.swing.JTextField txtHostName;
    private javax.swing.JTextField txtPortNumber;
    // End of variables declaration//GEN-END:variables
}
