/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesstotextconvert;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utility.SetupDatabase;

/**
 *
 * @author VSI-ANIK
 */
public class ConverterView extends javax.swing.JFrame {

    /**
     * Creates new form ConverterView
     */
    public ConverterView() {
        initComponents();
    }

    private String fromDate;
    private String toDate;
    private String fromDateDelete;
    private String toDateDelete;
    private String nitgenFromDate;
    private String nitgenToDate;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFromDate = new javax.swing.JTextField();
        txtToDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnProcessStart = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCheckNitgenServer = new javax.swing.JCheckBox();
        jCheckNitgenServer1 = new javax.swing.JCheckBox();
        jCheckRTAserver = new javax.swing.JCheckBox();
        jCheckZKTserver = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteAttendenceData = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        radioBtnZkt = new javax.swing.JRadioButton();
        radioBtnRta = new javax.swing.JRadioButton();
        txtToDateDelete = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFromDateDelete = new javax.swing.JTextField();
        radioBtnNitgen = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSetup = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conveter");
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 224));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Copyright @2012 Vistasoft IT Bangladesh Ltd.");

        jPanel3.setBackground(new java.awt.Color(255, 255, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Date Format:  DDMMYYYY or 31112019");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Start Date:");

        txtFromDate.setToolTipText("Type Date & Press Enter");
        txtFromDate.setSelectionEnd(10);
        txtFromDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFromDateMouseClicked(evt);
            }
        });
        txtFromDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFromDateKeyPressed(evt);
            }
        });

        txtToDate.setToolTipText("Type Date & Press Enter");
        txtToDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtToDateMouseClicked(evt);
            }
        });
        txtToDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtToDateKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("End Date:");

        lblMsg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(102, 0, 0));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsg.setText("Please wait, This Process Take Some");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Time Don't Cancel Before Complete");

        btnProcessStart.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnProcessStart.setText("Convert");
        btnProcessStart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProcessStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessStartActionPerformed(evt);
            }
        });

        jCheckNitgenServer.setBackground(new java.awt.Color(255, 255, 192));
        jCheckNitgenServer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckNitgenServer.setText("NITGEN");

        jCheckNitgenServer1.setBackground(new java.awt.Color(255, 255, 192));
        jCheckNitgenServer1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckNitgenServer1.setText("UNIS");

        jCheckRTAserver.setBackground(new java.awt.Color(255, 255, 192));
        jCheckRTAserver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckRTAserver.setText("RTA");

        jCheckZKTserver.setBackground(new java.awt.Color(255, 255, 192));
        jCheckZKTserver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckZKTserver.setText("ZKT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckZKTserver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckRTAserver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckNitgenServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckNitgenServer1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckZKTserver)
                    .addComponent(jCheckRTAserver)
                    .addComponent(jCheckNitgenServer)
                    .addComponent(jCheckNitgenServer1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProcessStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFromDate)
                            .addComponent(txtToDate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMsg)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProcessStart, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        btnDeleteAttendenceData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteAttendenceData.setText("Delete");
        btnDeleteAttendenceData.setPreferredSize(new java.awt.Dimension(127, 25));
        btnDeleteAttendenceData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAttendenceDataActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Delete Data");

        radioBtnZkt.setBackground(new java.awt.Color(255, 255, 192));
        buttonGroup1.add(radioBtnZkt);
        radioBtnZkt.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        radioBtnZkt.setText("ZKT");

        radioBtnRta.setBackground(new java.awt.Color(255, 255, 192));
        buttonGroup1.add(radioBtnRta);
        radioBtnRta.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        radioBtnRta.setText("RTA");

        txtToDateDelete.setToolTipText("Type Date & Press Enter");
        txtToDateDelete.setSelectionEnd(10);
        txtToDateDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtToDateDeleteKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TO");

        txtFromDateDelete.setToolTipText("Type Date & Press Enter");
        txtFromDateDelete.setSelectionEnd(10);
        txtFromDateDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFromDateDeleteKeyPressed(evt);
            }
        });

        radioBtnNitgen.setBackground(new java.awt.Color(255, 255, 192));
        buttonGroup1.add(radioBtnNitgen);
        radioBtnNitgen.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        radioBtnNitgen.setText("NITGEN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteAttendenceData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFromDateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtToDateDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(radioBtnZkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioBtnRta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioBtnNitgen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtFromDateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(txtToDateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(radioBtnZkt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnRta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnNitgen)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteAttendenceData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 192));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 16)); // NOI18N
        jLabel6.setText(" Data Converter ( VSI )");
        jLabel6.setPreferredSize(new java.awt.Dimension(222, 27));

        btnSetup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSetup.setText("Setup");
        btnSetup.setToolTipText("Setup -- Server");
        btnSetup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSetup.setContentAreaFilled(false);
        btnSetup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtToDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToDateKeyPressed
        // TODO add your handling code here:
        // if user press enter then
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER)&&(txtToDate.getText().length()==8)) {

            toDate = txtToDate.getText(); // get to date
            // make final string
            String finToDate = toDate.substring(2, 4) + "/" + toDate.substring(0, 2) + "/" + toDate.substring(4, toDate.length());
            //System.out.println(finToDate);
            txtToDate.setText(finToDate); // set the date

            btnProcessStart.requestFocus(); // request next work
        }
    }//GEN-LAST:event_txtToDateKeyPressed

    private void txtFromDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFromDateKeyPressed
        // TODO add your handling code here:
        // when user press enter then we format the date
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER)&&(txtFromDate.getText().length()==8)) {
            fromDate = txtFromDate.getText();
            String finFromDate = fromDate.substring(2, 4) + "/" + fromDate.substring(0, 2) + "/" + fromDate.substring(4, fromDate.length());
            //System.out.println(finFromDate);
            txtFromDate.setText(finFromDate);

            txtToDate.requestFocus();
        }
    }//GEN-LAST:event_txtFromDateKeyPressed

    private void btnProcessStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessStartActionPerformed
        if (jCheckNitgenServer.isSelected() || jCheckRTAserver.isSelected() || jCheckZKTserver.isSelected()) {
            // TODO add your handling code here:
            // create object
            ConverterCore converterCore = new ConverterCore();
            // make final date format for RTA
            String rtaFromDate = fromDate.substring(4, fromDate.length()) + fromDate.substring(2, 4) + fromDate.substring(0, 2);
            // make final date format for RTA
            String rtaToDate = toDate.substring(4, toDate.length()) + toDate.substring(2, 4) + toDate.substring(0, 2);
            // make final date for nitgen
            nitgenFromDate = fromDate.substring(4, fromDate.length()) + "-" + fromDate.substring(2, 4) + "-" + fromDate.substring(0, 2);
            // make final date for nitgen
            nitgenToDate = toDate.substring(4, toDate.length()) + "-" + toDate.substring(2, 4) + "-" + toDate.substring(0, 2);

            // check the date is valied
            if (txtFromDate.getText().length() == 10 && txtToDate.getText().length() == 10) {

                try {
                    converterCore.txtConverter(
                            txtFromDate.getText().length()>8?txtFromDate.getText():"0",
                            txtToDate.getText().length()>8?txtToDate.getText():"0",
                            rtaFromDate,
                            rtaToDate,
                            nitgenFromDate,
                            nitgenToDate,
                            jCheckZKTserver.isSelected(),
                            jCheckRTAserver.isSelected(),
                            jCheckNitgenServer.isSelected()
                    );
                    
                    // lblProgressBar.setText(" ");
                } catch (IOException ex) {
                    Logger.getLogger(ConverterView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Date Format Not Match",
                        ":: Date Error :: ", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Select Any Option",
                    "Select Option", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnProcessStartActionPerformed

    private void btnDeleteAttendenceDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAttendenceDataActionPerformed
        // TODO add your handling code here:        
        DataDelete core = new DataDelete();
        if (txtFromDateDelete.getText().length() == 10 && txtToDateDelete.getText().length() == 10
                && (radioBtnZkt.isSelected() || radioBtnRta.isSelected() || radioBtnNitgen.isSelected())) {

            if (radioBtnZkt.isSelected()) {
                core.deleteAttendenceDataInAccessDb(txtFromDateDelete.getText(), txtToDateDelete.getText());
            } else if (radioBtnRta.isSelected()) {
                core.deleteAttendenceFromRmsServer(fromDateDelete, toDateDelete);
            } else if (radioBtnNitgen.isSelected()) {
                core.deleteAttendenceFromNitgen(nitgenFromDate, nitgenToDate);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Select Any Option",
                    "Select Option", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteAttendenceDataActionPerformed

    private void txtToDateDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToDateDeleteKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String tempDate = txtToDateDelete.getText(); // get to date
            // make final string
            String finFromDate = tempDate.substring(2, 4) + "/" + tempDate.substring(0, 2) + "/" + tempDate.substring(4, tempDate.length());
            //System.out.println(finFromDate);
            // make final date for nitgen
            nitgenToDate = tempDate.substring(4, tempDate.length()) + "-" + tempDate.substring(2, 4) + "-" + tempDate.substring(0, 2);
            //System.out.println(nitgenToDate);

            txtToDateDelete.setText(finFromDate); // set the date
            toDateDelete = tempDate.substring(4, tempDate.length()) + tempDate.substring(2, 4) + tempDate.substring(0, 2);
            btnDeleteAttendenceData.requestFocus(); // request next work
        }

    }//GEN-LAST:event_txtToDateDeleteKeyPressed

    private void txtFromDateDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFromDateDeleteKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String tempDate = txtFromDateDelete.getText(); // get to date
            // make final string
            String finFromDate = tempDate.substring(2, 4) + "/" + tempDate.substring(0, 2) + "/" + tempDate.substring(4, tempDate.length());
            //System.out.println(finFromDate);
            // make final date for nitgen
            nitgenFromDate = tempDate.substring(4, tempDate.length()) + "-" + tempDate.substring(2, 4) + "-" + tempDate.substring(0, 2);
            //System.out.println(nitgenFromDate);
            txtFromDateDelete.setText(finFromDate); // set the date
            fromDateDelete = tempDate.substring(4, tempDate.length()) + tempDate.substring(2, 4) + tempDate.substring(0, 2);
            txtToDateDelete.requestFocus(); // request next work
        }

    }//GEN-LAST:event_txtFromDateDeleteKeyPressed

    private void btnSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetupActionPerformed
        // TODO add your handling code here:
        new SetupDatabase().setVisible(true);
    }//GEN-LAST:event_btnSetupActionPerformed

    private void txtFromDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFromDateMouseClicked
        // TODO add your handling code here:
        txtFromDate.setText("");
        txtToDate.setText("");
    }//GEN-LAST:event_txtFromDateMouseClicked

    private void txtToDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtToDateMouseClicked
        // TODO add your handling code here:
        txtToDate.setText("");
    }//GEN-LAST:event_txtToDateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAttendenceData;
    private javax.swing.JButton btnProcessStart;
    private javax.swing.JButton btnSetup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckNitgenServer;
    private javax.swing.JCheckBox jCheckNitgenServer1;
    private javax.swing.JCheckBox jCheckRTAserver;
    private javax.swing.JCheckBox jCheckZKTserver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JRadioButton radioBtnNitgen;
    private javax.swing.JRadioButton radioBtnRta;
    private javax.swing.JRadioButton radioBtnZkt;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtFromDateDelete;
    private javax.swing.JTextField txtToDate;
    private javax.swing.JTextField txtToDateDelete;
    // End of variables declaration//GEN-END:variables
}
