/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Anik
 * Created: Jul 17, 2020
 */
---- CREATE TABLE
CREATE TABLE TB_SUBMITED_BILL (
ID          NUMBER NOT NULL UNIQUE,
BILL_DATE   VARCHAR2(50 BYTE),
BILL_NUMBER	VARCHAR2(50 BYTE),
COM_NAME    VARCHAR2(250 BYTE),
AMOUNT      FLOAT(2),
BILL_TYPE	VARCHAR2(50 BYTE),
COLLECTED   VARCHAR2(10 BYTE) DEFAULT 'NO'
);

---  INSERT DATA IN TABLE
INSERT INTO TB_SUBMITED_BILL (ID,BILL_DATE,BILL_NUMBER,COM_NAME,AMOUNT,BILL_TYPE) 
VALUES (1,'12/01/2020','012020','VSI',5000,'MONTHLY-BILL');

--- CREATE TRIGGER
CREATE OR REPLACE TRIGGER AUTO_INCREMENT_SUBMITED_ID
BEFORE INSERT
	   ON TB_SUBMITED_BILL
	   FOR EACH ROW
	   
DECLARE
	   TEMP_VER NUMBER:=0;

BEGIN
	 SELECT MAX(ID) INTO TEMP_VER FROM TB_SUBMITED_BILL;
	 :NEW.ID:=(TEMP_VER+1);
END;
/

--- SELECT DATA
SELECT * FROM TB_SUBMITED_BILL