/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportgenerator.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.JFrame;
import reportgenerator.view.subwindow.AdvanceAmountEntry;
import reportgenerator.view.subwindow.ReportGenerateHardware;
import reportgenerator.view.subwindow.ReportGenerateSoftware;
import reportgenerator.view.subwindow.SubmitedPanddingBill;

/**
 *
 * @author Anik
 */
public class MainWorkingWindow extends javax.swing.JFrame {

    private String savingLoc = "D:\\";
    //private String savingLoc = "\\\\192.168.1.210\\monthly_online_bill_and_quotation\\";
    private String configComapnyListUrl = "setup\\CompanyName.txt";
    private String configPendingBillList = "setup\\PandingList.txt";

    private int hightOfMainPen;
    private int widthOfMainPen;
    

    /**
     * Creates new form MainWorkingWindow
     */
    public MainWorkingWindow() {

        initComponents();
        mainPen.setLayout(new BorderLayout(50, 50));

        Dimension DimMax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(DimMax);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        hightOfMainPen=mainPen.getHeight();
        widthOfMainPen=mainPen.getWidth();
        
        lblShowLogo.setLocation(10,this.getHeight()-20);
        lblCopyRightTeg.setLocation(this.getWidth()-10,this.getHeight()-10);
        //lblShowCompany.setSize(DimMax.width, 80);

        //subPenOfReportGenerateSoftware.setLayout(new GridLayout(1,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penReportGenerateSoftware = new javax.swing.JInternalFrame();
        subPenOfReportGenerateSoftware = new javax.swing.JPanel();
        penReportGenerateHardware = new javax.swing.JInternalFrame();
        subPenOfReportGenerateHardware = new javax.swing.JPanel();
        penEntryAdvanceAmount = new javax.swing.JInternalFrame();
        subPenOfEntryAdvanceAmount = new javax.swing.JPanel();
        penSubmitPanddingBill = new javax.swing.JInternalFrame();
        subPenOfSubmitPanddingBill = new javax.swing.JPanel();
        mainPen = new javax.swing.JPanel();
        lblShowCompany = new javax.swing.JLabel();
        lblCopyRightTeg = new javax.swing.JLabel();
        lblShowLogo = new javax.swing.JLabel();
        lblShowReord = new javax.swing.JLabel();
        lblShowReord2 = new javax.swing.JLabel();
        lblShowReord3 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuGenerate = new javax.swing.JMenu();
        manuItemMakeSoftwareQutAndBill = new javax.swing.JMenuItem();
        manuItemHardwareQutAndBill = new javax.swing.JMenuItem();
        menuEntry = new javax.swing.JMenu();
        manuItemEntryAdvanceAmount = new javax.swing.JMenuItem();
        manuItemSubmitPanddingBill = new javax.swing.JMenuItem();

        penReportGenerateSoftware.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        penReportGenerateSoftware.setClosable(true);
        penReportGenerateSoftware.setMaximizable(true);
        penReportGenerateSoftware.setResizable(true);
        penReportGenerateSoftware.setTitle("Make Software Qut & Bill");
        penReportGenerateSoftware.setToolTipText("Make Software Qut & Bill");
        penReportGenerateSoftware.setVisible(true);
        penReportGenerateSoftware.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penReportGenerateSoftwareInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout subPenOfReportGenerateSoftwareLayout = new javax.swing.GroupLayout(subPenOfReportGenerateSoftware);
        subPenOfReportGenerateSoftware.setLayout(subPenOfReportGenerateSoftwareLayout);
        subPenOfReportGenerateSoftwareLayout.setHorizontalGroup(
            subPenOfReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfReportGenerateSoftwareLayout.setVerticalGroup(
            subPenOfReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penReportGenerateSoftwareLayout = new javax.swing.GroupLayout(penReportGenerateSoftware.getContentPane());
        penReportGenerateSoftware.getContentPane().setLayout(penReportGenerateSoftwareLayout);
        penReportGenerateSoftwareLayout.setHorizontalGroup(
            penReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penReportGenerateSoftwareLayout.setVerticalGroup(
            penReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penReportGenerateHardware.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        penReportGenerateHardware.setClosable(true);
        penReportGenerateHardware.setMaximizable(true);
        penReportGenerateHardware.setResizable(true);
        penReportGenerateHardware.setTitle("Make Hardware Qut & Bill");
        penReportGenerateHardware.setToolTipText("Make Hardware Qut & Bill");
        penReportGenerateHardware.setVisible(true);
        penReportGenerateHardware.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penReportGenerateHardwareInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout subPenOfReportGenerateHardwareLayout = new javax.swing.GroupLayout(subPenOfReportGenerateHardware);
        subPenOfReportGenerateHardware.setLayout(subPenOfReportGenerateHardwareLayout);
        subPenOfReportGenerateHardwareLayout.setHorizontalGroup(
            subPenOfReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfReportGenerateHardwareLayout.setVerticalGroup(
            subPenOfReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penReportGenerateHardwareLayout = new javax.swing.GroupLayout(penReportGenerateHardware.getContentPane());
        penReportGenerateHardware.getContentPane().setLayout(penReportGenerateHardwareLayout);
        penReportGenerateHardwareLayout.setHorizontalGroup(
            penReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateHardware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penReportGenerateHardwareLayout.setVerticalGroup(
            penReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateHardware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penEntryAdvanceAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penEntryAdvanceAmount.setClosable(true);
        penEntryAdvanceAmount.setMaximizable(true);
        penEntryAdvanceAmount.setResizable(true);
        penEntryAdvanceAmount.setTitle("Make Hardware Qut & Bill");
        penEntryAdvanceAmount.setToolTipText("Make Hardware Qut & Bill");
        penEntryAdvanceAmount.setVisible(true);
        penEntryAdvanceAmount.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penEntryAdvanceAmountInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout subPenOfEntryAdvanceAmountLayout = new javax.swing.GroupLayout(subPenOfEntryAdvanceAmount);
        subPenOfEntryAdvanceAmount.setLayout(subPenOfEntryAdvanceAmountLayout);
        subPenOfEntryAdvanceAmountLayout.setHorizontalGroup(
            subPenOfEntryAdvanceAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfEntryAdvanceAmountLayout.setVerticalGroup(
            subPenOfEntryAdvanceAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penEntryAdvanceAmountLayout = new javax.swing.GroupLayout(penEntryAdvanceAmount.getContentPane());
        penEntryAdvanceAmount.getContentPane().setLayout(penEntryAdvanceAmountLayout);
        penEntryAdvanceAmountLayout.setHorizontalGroup(
            penEntryAdvanceAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryAdvanceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penEntryAdvanceAmountLayout.setVerticalGroup(
            penEntryAdvanceAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfEntryAdvanceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penSubmitPanddingBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));
        penSubmitPanddingBill.setClosable(true);
        penSubmitPanddingBill.setMaximizable(true);
        penSubmitPanddingBill.setResizable(true);
        penSubmitPanddingBill.setTitle("Make Hardware Qut & Bill");
        penSubmitPanddingBill.setToolTipText("Make Hardware Qut & Bill");
        penSubmitPanddingBill.setVisible(true);
        penSubmitPanddingBill.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                penSubmitPanddingBillInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout subPenOfSubmitPanddingBillLayout = new javax.swing.GroupLayout(subPenOfSubmitPanddingBill);
        subPenOfSubmitPanddingBill.setLayout(subPenOfSubmitPanddingBillLayout);
        subPenOfSubmitPanddingBillLayout.setHorizontalGroup(
            subPenOfSubmitPanddingBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfSubmitPanddingBillLayout.setVerticalGroup(
            subPenOfSubmitPanddingBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penSubmitPanddingBillLayout = new javax.swing.GroupLayout(penSubmitPanddingBill.getContentPane());
        penSubmitPanddingBill.getContentPane().setLayout(penSubmitPanddingBillLayout);
        penSubmitPanddingBillLayout.setHorizontalGroup(
            penSubmitPanddingBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfSubmitPanddingBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penSubmitPanddingBillLayout.setVerticalGroup(
            penSubmitPanddingBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfSubmitPanddingBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        mainPen.setBackground(new java.awt.Color(255, 255, 224));

        lblShowCompany.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        lblShowCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowCompany.setText("Vistasoft IT Bangladesh Ltd.");

        lblCopyRightTeg.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        lblCopyRightTeg.setForeground(new java.awt.Color(255, 0, 51));
        lblCopyRightTeg.setText("@copyright: Vistasoft IT Bangladesh Ltd. / Anik paul");

        lblShowLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/logoWithFooterTxt-app-color02.png"))); // NOI18N

        javax.swing.GroupLayout mainPenLayout = new javax.swing.GroupLayout(mainPen);
        mainPen.setLayout(mainPenLayout);
        mainPenLayout.setHorizontalGroup(
            mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShowCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPenLayout.createSequentialGroup()
                .addComponent(lblShowLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCopyRightTeg))
        );
        mainPenLayout.setVerticalGroup(
            mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPenLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblShowCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(150, 150, 150)
                .addGroup(mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCopyRightTeg)
                    .addComponent(lblShowLogo)))
        );

        lblShowReord.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord.setText("Record 1/1");
        lblShowReord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblShowReord2.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord2.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord2.setText(" ");
        lblShowReord2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        lblShowReord3.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        lblShowReord3.setForeground(new java.awt.Color(102, 102, 102));
        lblShowReord3.setText(" ");
        lblShowReord3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        mainMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainMenuBar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mainMenuBar.setPreferredSize(new java.awt.Dimension(56, 30));

        menuGenerate.setText("| Generate");
        menuGenerate.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        menuGenerate.setIconTextGap(5);
        menuGenerate.setMargin(new java.awt.Insets(0, 0, 0, 10));

        manuItemMakeSoftwareQutAndBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemMakeSoftwareQutAndBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemMakeSoftwareQutAndBill.setText("Make Software Qut & Bill");
        manuItemMakeSoftwareQutAndBill.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemMakeSoftwareQutAndBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemMakeSoftwareQutAndBillActionPerformed(evt);
            }
        });
        menuGenerate.add(manuItemMakeSoftwareQutAndBill);

        manuItemHardwareQutAndBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemHardwareQutAndBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemHardwareQutAndBill.setText("Make Hardware Qut & Bill");
        manuItemHardwareQutAndBill.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemHardwareQutAndBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemHardwareQutAndBillActionPerformed(evt);
            }
        });
        menuGenerate.add(manuItemHardwareQutAndBill);

        mainMenuBar.add(menuGenerate);

        menuEntry.setText("| Entry");
        menuEntry.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        menuEntry.setMargin(new java.awt.Insets(0, 0, 0, 15));

        manuItemEntryAdvanceAmount.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemEntryAdvanceAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemEntryAdvanceAmount.setText("Entry Advance Amount");
        manuItemEntryAdvanceAmount.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemEntryAdvanceAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemEntryAdvanceAmountActionPerformed(evt);
            }
        });
        menuEntry.add(manuItemEntryAdvanceAmount);

        manuItemSubmitPanddingBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemSubmitPanddingBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemSubmitPanddingBill.setText("Submit Pandding Bill");
        manuItemSubmitPanddingBill.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemSubmitPanddingBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemSubmitPanddingBillActionPerformed(evt);
            }
        });
        menuEntry.add(manuItemSubmitPanddingBill);

        mainMenuBar.add(menuEntry);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblShowReord, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowReord2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowReord3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 682, Short.MAX_VALUE))
            .addComponent(mainPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShowReord)
                    .addComponent(lblShowReord2)
                    .addComponent(lblShowReord3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manuItemMakeSoftwareQutAndBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemMakeSoftwareQutAndBillActionPerformed
        // TODO add your handling code here:

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());

        for (int i = 3, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInReportGenerateSoftware();
        penReportGenerateSoftware.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penReportGenerateSoftware.setVisible(true);
        mainPen.add(penReportGenerateSoftware, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemMakeSoftwareQutAndBillActionPerformed

    private void manuItemHardwareQutAndBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemHardwareQutAndBillActionPerformed
        // TODO add your handling code here:

        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = 3, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInReportGenerateHardware();
        penReportGenerateHardware.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penReportGenerateHardware.setVisible(true);
        mainPen.add(penReportGenerateHardware, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();
    }//GEN-LAST:event_manuItemHardwareQutAndBillActionPerformed

    private void penReportGenerateSoftwareInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penReportGenerateSoftwareInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penReportGenerateSoftware);
        showLableInMainWindow();
    }//GEN-LAST:event_penReportGenerateSoftwareInternalFrameClosed

    private void penReportGenerateHardwareInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penReportGenerateHardwareInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penReportGenerateHardware);
        showLableInMainWindow();
    }//GEN-LAST:event_penReportGenerateHardwareInternalFrameClosed

    private void penEntryAdvanceAmountInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penEntryAdvanceAmountInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penEntryAdvanceAmount);
        showLableInMainWindow();
    }//GEN-LAST:event_penEntryAdvanceAmountInternalFrameClosed

    private void manuItemEntryAdvanceAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemEntryAdvanceAmountActionPerformed
        // TODO add your handling code here:
        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = 3, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInEntryAdvanceAmount();
        penEntryAdvanceAmount.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penEntryAdvanceAmount.setVisible(true);
        mainPen.add(penEntryAdvanceAmount, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemEntryAdvanceAmountActionPerformed

    private void penSubmitPanddingBillInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_penSubmitPanddingBillInternalFrameClosed
        // TODO add your handling code here:
        mainPen.remove(penSubmitPanddingBill);
        showLableInMainWindow();
    }//GEN-LAST:event_penSubmitPanddingBillInternalFrameClosed

    private void manuItemSubmitPanddingBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemSubmitPanddingBillActionPerformed
        // TODO add your handling code here:
        hideLableInMainWindow();
        //System.out.println(mainPen.getComponentCount());
        for (int i = 3, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInpenSubmitPanddingBill();
        penSubmitPanddingBill.setBounds(10, 10, widthOfMainPen, hightOfMainPen);
        penSubmitPanddingBill.setVisible(true);
        mainPen.add(penSubmitPanddingBill, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();
    }//GEN-LAST:event_manuItemSubmitPanddingBillActionPerformed

    private void addPenInReportGenerateSoftware() {
        subPenOfReportGenerateSoftware.setLayout(new GridLayout(1, 1));
        subPenOfReportGenerateSoftware.removeAll();
        subPenOfReportGenerateSoftware.add(new ReportGenerateSoftware(savingLoc, configComapnyListUrl, configPendingBillList));
        subPenOfReportGenerateSoftware.revalidate();
        subPenOfReportGenerateSoftware.repaint();
    }

    private void addPenInReportGenerateHardware() {
        subPenOfReportGenerateHardware.setLayout(new GridLayout(1, 1));
        subPenOfReportGenerateHardware.removeAll();
        subPenOfReportGenerateHardware.add(new ReportGenerateHardware(savingLoc, configComapnyListUrl, configPendingBillList));
        subPenOfReportGenerateHardware.revalidate();
        subPenOfReportGenerateHardware.repaint();
    }

    private void addPenInEntryAdvanceAmount() {
        subPenOfEntryAdvanceAmount.setLayout(new GridLayout(1,1));
        subPenOfEntryAdvanceAmount.removeAll();
        AdvanceAmountEntry amountEntry=new AdvanceAmountEntry();
        subPenOfEntryAdvanceAmount.add(amountEntry);
        subPenOfEntryAdvanceAmount.revalidate();
        subPenOfEntryAdvanceAmount.repaint();
    }
    
    private void addPenInpenSubmitPanddingBill(){
        subPenOfSubmitPanddingBill.setLayout(new GridLayout(1,1));
        subPenOfSubmitPanddingBill.removeAll();
        SubmitedPanddingBill panddingBill=new SubmitedPanddingBill(configComapnyListUrl);
        subPenOfSubmitPanddingBill.add(panddingBill);
        subPenOfSubmitPanddingBill.revalidate();
        subPenOfSubmitPanddingBill.repaint();
    }
    
    private void hideLableInMainWindow() {

        lblShowCompany.setVisible(false);
        lblCopyRightTeg.setVisible(false);
        lblShowLogo.setVisible(false);
    }

    private void showLableInMainWindow() {
        if (mainPen.getComponentCount() == 3) {
            lblShowCompany.setVisible(true);
            lblCopyRightTeg.setVisible(true);
            lblShowLogo.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWorkingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCopyRightTeg;
    private javax.swing.JLabel lblShowCompany;
    private javax.swing.JLabel lblShowLogo;
    private javax.swing.JLabel lblShowReord;
    private javax.swing.JLabel lblShowReord2;
    private javax.swing.JLabel lblShowReord3;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPen;
    private javax.swing.JMenuItem manuItemEntryAdvanceAmount;
    private javax.swing.JMenuItem manuItemHardwareQutAndBill;
    private javax.swing.JMenuItem manuItemMakeSoftwareQutAndBill;
    private javax.swing.JMenuItem manuItemSubmitPanddingBill;
    private javax.swing.JMenu menuEntry;
    private javax.swing.JMenu menuGenerate;
    private javax.swing.JInternalFrame penEntryAdvanceAmount;
    private javax.swing.JInternalFrame penReportGenerateHardware;
    private javax.swing.JInternalFrame penReportGenerateSoftware;
    private javax.swing.JInternalFrame penSubmitPanddingBill;
    private javax.swing.JPanel subPenOfEntryAdvanceAmount;
    private javax.swing.JPanel subPenOfReportGenerateHardware;
    private javax.swing.JPanel subPenOfReportGenerateSoftware;
    private javax.swing.JPanel subPenOfSubmitPanddingBill;
    // End of variables declaration//GEN-END:variables
}
