/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportgenerator.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.JFrame;
import reportgenerator.view.subwindow.ReportGenerateHardware;
import reportgenerator.view.subwindow.ReportGenerateSoftware;

/**
 *
 * @author Anik
 */
public class MainWorkingWindow extends javax.swing.JFrame {

     private String savingLoc = "D:\\";
    //private String savingLoc = "\\\\192.168.1.210\\monthly_online_bill_and_quotation\\";
    private String configComapnyListUrl = "setup\\CompanyName.txt";
    private String configPendingBillList = "setup\\PandingList.txt";
    
    private int hightOfReportGenerateSoftware;
    private int widthOfReportGenerateSoftware;
    private int hightOfReportGenerateHardware;
    private int widthOfReportGenerateHardware;

    /**
     * Creates new form MainWorkingWindow
     */
    public MainWorkingWindow() {
        initComponents();

        hightOfReportGenerateSoftware = penReportGenerateSoftware.getHeight();
        widthOfReportGenerateSoftware = penReportGenerateSoftware.getWidth();
        hightOfReportGenerateHardware = penReportGenerateHardware.getHeight();
        widthOfReportGenerateHardware = penReportGenerateHardware.getWidth();

        mainPen.setLayout(new BorderLayout(50, 50));
        
        Dimension DimMax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(DimMax);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //subPenOfReportGenerateSoftware.setLayout(new GridLayout(1,1));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penReportGenerateSoftware = new javax.swing.JInternalFrame();
        subPenOfReportGenerateSoftware = new javax.swing.JPanel();
        penReportGenerateHardware = new javax.swing.JInternalFrame();
        subPenOfReportGenerateHardware = new javax.swing.JPanel();
        mainPen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        menuGenerate = new javax.swing.JMenu();
        manuItemMakeSoftwareQutAndBill = new javax.swing.JMenuItem();
        manuItemHardwareQutAndBill = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        penReportGenerateSoftware.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        penReportGenerateSoftware.setClosable(true);
        penReportGenerateSoftware.setMaximizable(true);
        penReportGenerateSoftware.setResizable(true);
        penReportGenerateSoftware.setTitle("Make Software Qut & Bill");
        penReportGenerateSoftware.setToolTipText("Make Software Qut & Bill");
        penReportGenerateSoftware.setVisible(true);

        javax.swing.GroupLayout subPenOfReportGenerateSoftwareLayout = new javax.swing.GroupLayout(subPenOfReportGenerateSoftware);
        subPenOfReportGenerateSoftware.setLayout(subPenOfReportGenerateSoftwareLayout);
        subPenOfReportGenerateSoftwareLayout.setHorizontalGroup(
            subPenOfReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfReportGenerateSoftwareLayout.setVerticalGroup(
            subPenOfReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penReportGenerateSoftwareLayout = new javax.swing.GroupLayout(penReportGenerateSoftware.getContentPane());
        penReportGenerateSoftware.getContentPane().setLayout(penReportGenerateSoftwareLayout);
        penReportGenerateSoftwareLayout.setHorizontalGroup(
            penReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penReportGenerateSoftwareLayout.setVerticalGroup(
            penReportGenerateSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        penReportGenerateHardware.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        penReportGenerateHardware.setClosable(true);
        penReportGenerateHardware.setMaximizable(true);
        penReportGenerateHardware.setResizable(true);
        penReportGenerateHardware.setTitle("Make Hardware Qut & Bill");
        penReportGenerateHardware.setToolTipText("Make Hardware Qut & Bill");
        penReportGenerateHardware.setVisible(true);

        javax.swing.GroupLayout subPenOfReportGenerateHardwareLayout = new javax.swing.GroupLayout(subPenOfReportGenerateHardware);
        subPenOfReportGenerateHardware.setLayout(subPenOfReportGenerateHardwareLayout);
        subPenOfReportGenerateHardwareLayout.setHorizontalGroup(
            subPenOfReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        subPenOfReportGenerateHardwareLayout.setVerticalGroup(
            subPenOfReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout penReportGenerateHardwareLayout = new javax.swing.GroupLayout(penReportGenerateHardware.getContentPane());
        penReportGenerateHardware.getContentPane().setLayout(penReportGenerateHardwareLayout);
        penReportGenerateHardwareLayout.setHorizontalGroup(
            penReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateHardware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        penReportGenerateHardwareLayout.setVerticalGroup(
            penReportGenerateHardwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPenOfReportGenerateHardware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPen.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vistasoft IT Bangladesh Ltd.");

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("@copyright: Vistasoft IT Bangladesh Ltd.");

        javax.swing.GroupLayout mainPenLayout = new javax.swing.GroupLayout(mainPen);
        mainPen.setLayout(mainPenLayout);
        mainPenLayout.setHorizontalGroup(
            mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
            .addGroup(mainPenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );
        mainPenLayout.setVerticalGroup(
            mainPenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPenLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        mainMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainMenuBar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        mainMenuBar.setPreferredSize(new java.awt.Dimension(56, 30));

        menuGenerate.setText("| Generate");
        menuGenerate.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        menuGenerate.setIconTextGap(5);
        menuGenerate.setMargin(new java.awt.Insets(0, 0, 0, 10));

        manuItemMakeSoftwareQutAndBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemMakeSoftwareQutAndBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemMakeSoftwareQutAndBill.setText("Make Software Qut & Bill");
        manuItemMakeSoftwareQutAndBill.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemMakeSoftwareQutAndBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemMakeSoftwareQutAndBillActionPerformed(evt);
            }
        });
        menuGenerate.add(manuItemMakeSoftwareQutAndBill);

        manuItemHardwareQutAndBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        manuItemHardwareQutAndBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportgenerator/view/icon/arrow.png"))); // NOI18N
        manuItemHardwareQutAndBill.setText("Make Hardware Qut & Bill");
        manuItemHardwareQutAndBill.setMargin(new java.awt.Insets(0, 0, 10, 0));
        manuItemHardwareQutAndBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuItemHardwareQutAndBillActionPerformed(evt);
            }
        });
        menuGenerate.add(manuItemHardwareQutAndBill);

        mainMenuBar.add(menuGenerate);

        jMenu1.setText("| Exit");
        jMenu1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 0, 0, 15));
        mainMenuBar.add(jMenu1);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manuItemMakeSoftwareQutAndBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemMakeSoftwareQutAndBillActionPerformed
        // TODO add your handling code here:
        
        System.out.println(mainPen.getComponentCount());
        
        for (int i = 2, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }

        addPenInReportGenerateSoftware();
        penReportGenerateSoftware.setBounds(10, 10, widthOfReportGenerateSoftware, hightOfReportGenerateSoftware);
        penReportGenerateSoftware.setVisible(true);
        mainPen.add(penReportGenerateSoftware, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();

    }//GEN-LAST:event_manuItemMakeSoftwareQutAndBillActionPerformed

    private void manuItemHardwareQutAndBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuItemHardwareQutAndBillActionPerformed
        // TODO add your handling code here:
        System.out.println(mainPen.getComponentCount());
        for (int i = 2, j = 10; i < mainPen.getComponentCount(); i++, j += 100) {
            mainPen.getComponent(i).setBounds(mainPen.getWidth() - (mainPen.getWidth() - j), (mainPen.getHeight() - 50), 100, 50);
        }
        
        addPenInReportGenerateHardware();
        penReportGenerateHardware.setBounds(10, 10, widthOfReportGenerateHardware, hightOfReportGenerateHardware);
        penReportGenerateHardware.setVisible(true);
        mainPen.add(penReportGenerateHardware, BorderLayout.CENTER);
        mainPen.revalidate();
        mainPen.repaint();
    }//GEN-LAST:event_manuItemHardwareQutAndBillActionPerformed

    private void addPenInReportGenerateSoftware() {
        subPenOfReportGenerateSoftware.setLayout(new GridLayout(1, 1));
        subPenOfReportGenerateSoftware.removeAll();
        subPenOfReportGenerateSoftware.add(new ReportGenerateSoftware(savingLoc,configComapnyListUrl,configPendingBillList));
        subPenOfReportGenerateSoftware.revalidate();
        subPenOfReportGenerateSoftware.repaint();
    }

    private void addPenInReportGenerateHardware() {
        subPenOfReportGenerateHardware.setLayout(new GridLayout(1, 1));
        subPenOfReportGenerateHardware.removeAll();
        subPenOfReportGenerateHardware.add(new ReportGenerateHardware(savingLoc,configComapnyListUrl,configPendingBillList));
        subPenOfReportGenerateHardware.revalidate();
        subPenOfReportGenerateHardware.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWorkingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWorkingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPen;
    private javax.swing.JMenuItem manuItemHardwareQutAndBill;
    private javax.swing.JMenuItem manuItemMakeSoftwareQutAndBill;
    private javax.swing.JMenu menuGenerate;
    private javax.swing.JInternalFrame penReportGenerateHardware;
    private javax.swing.JInternalFrame penReportGenerateSoftware;
    private javax.swing.JPanel subPenOfReportGenerateHardware;
    private javax.swing.JPanel subPenOfReportGenerateSoftware;
    // End of variables declaration//GEN-END:variables
}
