/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportgenerator.view;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import reportgenerator.corefunction.WriteHardwareQut;
import reportgenerator.corefunction.WriteHardwareQutBill;
import reportgenerator.dao.HardwareQutComponent;

/**
 *
 * @author Anik
 */
public class MakeHardwareQutAndBill extends javax.swing.JFrame {

    private JTextField brandName[];
    private JTextField modelName[];
    private JTextField originName[];
    private JTextField warranty[];
    private JTextField faceCapacity[];
    private JTextField fingerCapacity[];
    private JTextField cardCapacity[];
    private JTextField eventLog[];
    private JTextField comWay[];
    private JTextField deviceQty[];
    private JTextField deviceUnitPrice[];
    private String date;
    private String companyName;
    private String companyAddress;
    private String url;

    List<HardwareQutComponent> listOfHarwareQut = new ArrayList<>();

    /**
     * Creates new form MakeHardwareQutAndBill
     *
     * @param date
     * @param comName
     * @param comAddress
     */
    public MakeHardwareQutAndBill(String date, String comName, String comAddress, String url) {
        this.date = date;
        this.companyName = comName;
        this.companyAddress = comAddress;
        this.url = url;

        initComponents();
        showListOfPenel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanShowList = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDtls9 = new javax.swing.JTextField();
        txtDtls1 = new javax.swing.JTextField();
        txtDtls3 = new javax.swing.JTextField();
        txtDtls2 = new javax.swing.JTextField();
        txtDtls5 = new javax.swing.JTextField();
        txtDtls8 = new javax.swing.JTextField();
        txtDtls10 = new javax.swing.JTextField();
        txtDtls6 = new javax.swing.JTextField();
        txtDtls4 = new javax.swing.JTextField();
        txtDtls7 = new javax.swing.JTextField();
        txtMoreDtls3 = new javax.swing.JTextField();
        txtMoreDtls1 = new javax.swing.JTextField();
        txtMoreDtls6 = new javax.swing.JTextField();
        txtMoreDtls7 = new javax.swing.JTextField();
        txtMoreDtls8 = new javax.swing.JTextField();
        txtMoreDtls2 = new javax.swing.JTextField();
        txtMoreDtls5 = new javax.swing.JTextField();
        txtMoreDtls9 = new javax.swing.JTextField();
        txtMoreDtls4 = new javax.swing.JTextField();
        txtMoreDtls10 = new javax.swing.JTextField();
        txtQty1 = new javax.swing.JTextField();
        txtQty5 = new javax.swing.JTextField();
        txtQty10 = new javax.swing.JTextField();
        txtQty4 = new javax.swing.JTextField();
        txtQty6 = new javax.swing.JTextField();
        txtQty9 = new javax.swing.JTextField();
        txtQty2 = new javax.swing.JTextField();
        txtQty3 = new javax.swing.JTextField();
        txtQty7 = new javax.swing.JTextField();
        txtQty8 = new javax.swing.JTextField();
        txtUnitPrice5 = new javax.swing.JTextField();
        txtUnitPrice8 = new javax.swing.JTextField();
        txtUnitPrice6 = new javax.swing.JTextField();
        txtUnitPrice10 = new javax.swing.JTextField();
        txtUnitPrice2 = new javax.swing.JTextField();
        txtUnitPrice1 = new javax.swing.JTextField();
        txtUnitPrice9 = new javax.swing.JTextField();
        txtUnitPrice3 = new javax.swing.JTextField();
        txtUnitPrice7 = new javax.swing.JTextField();
        txtUnitPrice4 = new javax.swing.JTextField();
        btnMakeHardwareQut = new javax.swing.JButton();
        txtHardwareBillNo = new javax.swing.JTextField();
        btnMakeHardwareQutBill = new javax.swing.JButton();
        comboQtyType1 = new javax.swing.JComboBox<>();
        comboQtyType2 = new javax.swing.JComboBox<>();
        comboQtyType3 = new javax.swing.JComboBox<>();
        comboQtyType4 = new javax.swing.JComboBox<>();
        comboQtyType5 = new javax.swing.JComboBox<>();
        comboQtyType6 = new javax.swing.JComboBox<>();
        comboQtyType7 = new javax.swing.JComboBox<>();
        comboQtyType8 = new javax.swing.JComboBox<>();
        comboQtyType9 = new javax.swing.JComboBox<>();
        comboQtyType10 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);

        javax.swing.GroupLayout jPanShowListLayout = new javax.swing.GroupLayout(jPanShowList);
        jPanShowList.setLayout(jPanShowListLayout);
        jPanShowListLayout.setHorizontalGroup(
            jPanShowListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        jPanShowListLayout.setVerticalGroup(
            jPanShowListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanShowList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Write Divice Info", jPanel4);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Dtls");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Dtls2");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Qty");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Unit Price");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDtls9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtDtls7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtMoreDtls10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        txtQty1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty1.setText("0");

        txtQty5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty5.setText("0");

        txtQty10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty10.setText("0");

        txtQty4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty4.setText("0");

        txtQty6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty6.setText("0");

        txtQty9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty9.setText("0");

        txtQty2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty2.setText("0");

        txtQty3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty3.setText("0");

        txtQty7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty7.setText("0");

        txtQty8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtQty8.setText("0");

        txtUnitPrice5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice5.setText("0");

        txtUnitPrice8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice8.setText("0");

        txtUnitPrice6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice6.setText("0");

        txtUnitPrice10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice10.setText("0");

        txtUnitPrice2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice2.setText("0");

        txtUnitPrice1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice1.setText("0");

        txtUnitPrice9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice9.setText("0");

        txtUnitPrice3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice3.setText("0");

        txtUnitPrice7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice7.setText("0");

        txtUnitPrice4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUnitPrice4.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(txtDtls10, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(txtDtls9)
                    .addComponent(txtDtls7)
                    .addComponent(txtDtls6)
                    .addComponent(txtDtls2)
                    .addComponent(txtDtls3)
                    .addComponent(txtDtls1)
                    .addComponent(txtDtls8)
                    .addComponent(txtDtls4)
                    .addComponent(txtDtls5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(txtMoreDtls8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMoreDtls1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMoreDtls2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMoreDtls3)
                    .addComponent(txtMoreDtls5)
                    .addComponent(txtMoreDtls6)
                    .addComponent(txtMoreDtls9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMoreDtls10)
                    .addComponent(txtMoreDtls7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMoreDtls4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtQty2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtQty1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQty10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQty7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQty9, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(txtQty5)
                                        .addComponent(txtQty6)
                                        .addComponent(txtQty8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(txtQty4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnitPrice3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtUnitPrice2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUnitPrice10)
                                .addComponent(txtUnitPrice9)
                                .addComponent(txtUnitPrice7)
                                .addComponent(txtUnitPrice5)
                                .addComponent(txtUnitPrice6)
                                .addComponent(txtUnitPrice8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtUnitPrice4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                            .addComponent(txtUnitPrice1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(1, 1, 1))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDtls1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDtls7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMoreDtls7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtQty7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUnitPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtls10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtls3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQty4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnitPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMoreDtls4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDtls4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtls5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoreDtls6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtls6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        btnMakeHardwareQut.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnMakeHardwareQut.setText("Make Qutitoin");
        btnMakeHardwareQut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeHardwareQutActionPerformed(evt);
            }
        });

        txtHardwareBillNo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        btnMakeHardwareQutBill.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnMakeHardwareQutBill.setText("Make Qutitoin Bill");
        btnMakeHardwareQutBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeHardwareQutBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtHardwareBillNo)
                        .addGap(28, 28, 28)
                        .addComponent(btnMakeHardwareQut, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMakeHardwareQutBill, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMakeHardwareQutBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHardwareBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMakeHardwareQut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("No-Detls   --------------------------------------------------------------------------------------   Amount");

        comboQtyType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        comboQtyType10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "CM", "M" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboQtyType1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQtyType2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType4, javax.swing.GroupLayout.Alignment.TRAILING, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType5, javax.swing.GroupLayout.Alignment.TRAILING, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType6, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType7, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType8, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType9, 0, 110, Short.MAX_VALUE)
                    .addComponent(comboQtyType10, 0, 110, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(comboQtyType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(comboQtyType8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQtyType10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Write Other Item", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeHardwareQutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeHardwareQutActionPerformed
        // TODO add your handling code here:
        showData(setData());

        File selectedFile = new File(url);

        if (new WriteHardwareQut().writeHardwareQutInPdfFile(setData(), selectedFile)) {
            System.out.println("Qutation make --> ");
            JOptionPane.showMessageDialog(null, "Qutation Is Generated.",
                    ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Qutation Isn't Generated.",
                    ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnMakeHardwareQutActionPerformed

    private void btnMakeHardwareQutBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeHardwareQutBillActionPerformed
        // TODO add your handling code here:
        
        File selectedFile = new File(url);

        if (new WriteHardwareQutBill().writeHardwareQutBillInPdfFile(setData(), selectedFile)) {
            System.out.println("Qutation make --> ");
            JOptionPane.showMessageDialog(null, "Qutation Is Generated.",
                    ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Qutation Isn't Generated.",
                    ":: Success :: ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMakeHardwareQutBillActionPerformed

    private void showListOfPenel() {
        JPanel pan[] = new JPanel[10];
        jPanShowList.setLayout(new GridLayout(0, 1, 20, 20));

        brandName = new JTextField[5];
        modelName = new JTextField[5];
        originName = new JTextField[5];
        warranty = new JTextField[5];
        faceCapacity = new JTextField[5];
        fingerCapacity = new JTextField[5];
        cardCapacity = new JTextField[5];
        eventLog = new JTextField[5];
        comWay = new JTextField[5];
        deviceQty = new JTextField[5];
        deviceUnitPrice = new JTextField[5];

        for (int i = 0; i < 5; i++) {

            pan[i] = new JPanel();
            pan[i].setLayout(new GridLayout(1, 6, 5, 15));

            String label[] = {"Brand:", "Model:", "Origin:", "Warranty:", "Face Cap:", "Finger Cap:", "Card Cap:",
                "Event Log:", "Com way:", "Qty:", "Unit Price:"};

            brandName[i] = new JTextField();
            brandName[i].setBorder(new TitledBorder(label[0]));
            modelName[i] = new JTextField();
            modelName[i].setBorder(new TitledBorder(label[1]));
            originName[i] = new JTextField();
            originName[i].setBorder(new TitledBorder(label[2]));
            warranty[i] = new JTextField("0");
            warranty[i].setBorder(new TitledBorder(label[3]));
            faceCapacity[i] = new JTextField("0");
            faceCapacity[i].setBorder(new TitledBorder(label[4]));
            fingerCapacity[i] = new JTextField("0");
            fingerCapacity[i].setBorder(new TitledBorder(label[5]));
            cardCapacity[i] = new JTextField("0");
            cardCapacity[i].setBorder(new TitledBorder(label[6]));
            eventLog[i] = new JTextField("0");
            eventLog[i].setBorder(new TitledBorder(label[7]));
            comWay[i] = new JTextField();
            comWay[i].setBorder(new TitledBorder(label[8]));
            deviceQty[i] = new JTextField("0");
            deviceQty[i].setBorder(new TitledBorder(label[9]));
            deviceUnitPrice[i] = new JTextField("0");
            deviceUnitPrice[i].setBorder(new TitledBorder(label[10]));

            pan[i].add(brandName[i]);
            pan[i].add(modelName[i]);
            pan[i].add(originName[i]);
            pan[i].add(warranty[i]);
            pan[i].add(faceCapacity[i]);
            pan[i].add(fingerCapacity[i]);
            pan[i].add(cardCapacity[i]);
            pan[i].add(eventLog[i]);
            pan[i].add(comWay[i]);
            pan[i].add(deviceQty[i]);
            pan[i].add(deviceUnitPrice[i]);
            pan[i].revalidate();
            pan[i].repaint();
            pan[i].setBackground(Color.WHITE);

            jPanShowList.add(pan[i]);
            jPanShowList.revalidate();
            jPanShowList.repaint();
        }

    }

    private List<HardwareQutComponent> setData() {

        List<HardwareQutComponent> listOfComponent = new ArrayList<>();
        String tempStr = "";

        int i = 0;
        while (i < 5) {

            if (!modelName[i].getText().isEmpty()) {
                HardwareQutComponent component = new HardwareQutComponent();

                component.setDate(date);
                component.setCompanyName(companyName);
                component.setBillNo(txtHardwareBillNo.getText());
                component.setAddress(companyAddress);
                component.setBrand(brandName[i].getText());
                component.setModel(modelName[i].getText());
                component.setOrigin(originName[i].getText());
                component.setWarranty(Integer.parseInt(warranty[i].getText()));
                component.setFaceCapacity(Integer.parseInt(faceCapacity[i].getText()));
                component.setFingerCapacity(Integer.parseInt(fingerCapacity[i].getText()));
                component.setCardCapacity(Integer.parseInt(cardCapacity[i].getText()));
                component.setEventLog(Integer.parseInt(eventLog[i].getText()));
                component.setCommunicationWay(comWay[i].getText());
                int dvcQty = Integer.parseInt(deviceQty[i].getText());
                component.setDeviceQty(dvcQty);
                float dvcUnitPrice = Float.valueOf(deviceUnitPrice[i].getText());
                component.setDeviceUnitPrice(dvcUnitPrice);
                component.setDeviceTotalPrice(dvcUnitPrice * dvcQty);

                listOfComponent.add(component);
            }
            i++;
        }

        if (!txtDtls1.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls1.getText());
            component.setDtls02(txtMoreDtls1.getText());
            int qty = Integer.parseInt(txtQty1.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice1.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType1.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls2.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls2.getText());
            component.setDtls02(txtMoreDtls2.getText());
            int qty = Integer.parseInt(txtQty2.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice2.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType2.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls3.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls3.getText());
            component.setDtls02(txtMoreDtls3.getText());
            int qty = Integer.parseInt(txtQty3.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice3.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType3.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls4.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls4.getText());
            component.setDtls02(txtMoreDtls4.getText());
            int qty = Integer.parseInt(txtQty4.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice4.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType4.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls5.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls5.getText());
            component.setDtls02(txtMoreDtls5.getText());
            int qty = Integer.parseInt(txtQty5.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice5.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType5.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls6.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls6.getText());
            component.setDtls02(txtMoreDtls6.getText());
            int qty = Integer.parseInt(txtQty6.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice6.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType6.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls7.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls7.getText());
            component.setDtls02(txtMoreDtls7.getText());
            int qty = Integer.parseInt(txtQty7.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice7.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType7.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls8.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls8.getText());
            component.setDtls02(txtMoreDtls8.getText());
            int qty = Integer.parseInt(txtQty8.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice8.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType8.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls9.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls9.getText());
            component.setDtls02(txtMoreDtls9.getText());
            int qty = Integer.parseInt(txtQty9.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice9.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType9.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        if (!txtDtls10.getText().isEmpty()) {
            HardwareQutComponent component = new HardwareQutComponent();
            component.setDate(date);
            component.setCompanyName(companyName);
            component.setAddress(companyAddress);
            component.setBillNo(txtHardwareBillNo.getText());
            component.setBrand(tempStr);
            component.setDtls01(txtDtls10.getText());
            component.setDtls02(txtMoreDtls10.getText());
            int qty = Integer.parseInt(txtQty10.getText());
            component.setQty(qty);
            float price = Float.parseFloat(txtUnitPrice10.getText());
            component.setUnitPrice(price);
            float totalPrice = (price * qty);
            component.setTotalPrice(totalPrice);
            component.setQtyType(comboQtyType10.getSelectedItem().toString());
            listOfComponent.add(component);
        }

        return listOfComponent;
    }

    private void showData(List<HardwareQutComponent> list) {
        System.out.println(list.size());

        for (int i = 0; i < list.size(); i++) {
            try {
                if (!list.get(i).getBrand().isEmpty()) {
                    System.out.println(list.get(i).getBrand());
                    System.out.println(list.get(i).getModel());
                    System.out.println(list.get(i).getFingerCapacity());
                    System.out.println(list.get(i).getCardCapacity());
                    System.out.println(list.get(i).getCommunicationWay());
                } else if (!list.get(i).getDtls01().isEmpty()) {
                    System.out.println(list.get(i).getDtls01());
                    System.out.println(list.get(i).getDtls02());
                    System.out.println(list.get(i).getTotalPrice());
                } else {
                    break;
                }
            } catch (NullPointerException e) {
                e.printStackTrace();
            }
            System.out.println("===========================================");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeHardwareQut;
    private javax.swing.JButton btnMakeHardwareQutBill;
    private javax.swing.JComboBox<String> comboQtyType1;
    private javax.swing.JComboBox<String> comboQtyType10;
    private javax.swing.JComboBox<String> comboQtyType2;
    private javax.swing.JComboBox<String> comboQtyType3;
    private javax.swing.JComboBox<String> comboQtyType4;
    private javax.swing.JComboBox<String> comboQtyType5;
    private javax.swing.JComboBox<String> comboQtyType6;
    private javax.swing.JComboBox<String> comboQtyType7;
    private javax.swing.JComboBox<String> comboQtyType8;
    private javax.swing.JComboBox<String> comboQtyType9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanShowList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDtls1;
    private javax.swing.JTextField txtDtls10;
    private javax.swing.JTextField txtDtls2;
    private javax.swing.JTextField txtDtls3;
    private javax.swing.JTextField txtDtls4;
    private javax.swing.JTextField txtDtls5;
    private javax.swing.JTextField txtDtls6;
    private javax.swing.JTextField txtDtls7;
    private javax.swing.JTextField txtDtls8;
    private javax.swing.JTextField txtDtls9;
    private javax.swing.JTextField txtHardwareBillNo;
    private javax.swing.JTextField txtMoreDtls1;
    private javax.swing.JTextField txtMoreDtls10;
    private javax.swing.JTextField txtMoreDtls2;
    private javax.swing.JTextField txtMoreDtls3;
    private javax.swing.JTextField txtMoreDtls4;
    private javax.swing.JTextField txtMoreDtls5;
    private javax.swing.JTextField txtMoreDtls6;
    private javax.swing.JTextField txtMoreDtls7;
    private javax.swing.JTextField txtMoreDtls8;
    private javax.swing.JTextField txtMoreDtls9;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQty10;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtQty3;
    private javax.swing.JTextField txtQty4;
    private javax.swing.JTextField txtQty5;
    private javax.swing.JTextField txtQty6;
    private javax.swing.JTextField txtQty7;
    private javax.swing.JTextField txtQty8;
    private javax.swing.JTextField txtQty9;
    private javax.swing.JTextField txtUnitPrice1;
    private javax.swing.JTextField txtUnitPrice10;
    private javax.swing.JTextField txtUnitPrice2;
    private javax.swing.JTextField txtUnitPrice3;
    private javax.swing.JTextField txtUnitPrice4;
    private javax.swing.JTextField txtUnitPrice5;
    private javax.swing.JTextField txtUnitPrice6;
    private javax.swing.JTextField txtUnitPrice7;
    private javax.swing.JTextField txtUnitPrice8;
    private javax.swing.JTextField txtUnitPrice9;
    // End of variables declaration//GEN-END:variables
}
