/*
 * Copyright (C) 2020 VSI-ANIK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package utility;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author VSI-ANIK
 */
public class SetupDatabase extends javax.swing.JFrame {

    private String zktDatabaseLink;
    private String rtaDatabaseLink;
    private String serverFile;
    private String userNameFile;
    private String passwordFile;
    private String dbName;
    private String zktPath;
    private String rtaPath;
    private KeyList keyList = new KeyList();

    /**
     * Creates new form SetupDatabase
     */
    public SetupDatabase() {
        initComponents();

        holdOldData();
        jTxtDbName.setText(dbName);
        jTxtPassword.setText(passwordFile);
        jTxtServerName.setText(serverFile);
        jTxtUserName.setText(userNameFile);

    }

    private void holdOldData() {

//        try {
        try (InputStream input = new FileInputStream("config.properties")) {

            Properties properties = new Properties();
            properties.load(input);
            serverFile = properties.getProperty(keyList.KEY_SERVER_NAME);
            userNameFile = properties.getProperty(keyList.KEY_USER_NAME);
            passwordFile = properties.getProperty(keyList.KEY_USER_PASSWORD);
            dbName = properties.getProperty(keyList.KEY_DATABSE_NAME);
            zktPath = properties.getProperty(keyList.KEY_ZKT_LINK);
            rtaPath = properties.getProperty(keyList.KEY_RTA_LINK);
            properties.clear();
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    null, "Check File Exists? Or Save Information",
                    ":: File Not Found :: ", JOptionPane.INFORMATION_MESSAGE);
        }

        // call file.
//            File file = new File("D:\\AccessToTextConvert\\config.txt");
//            Scanner scan = new Scanner(file); // call scanner class
//
//            if (file.exists()) {
//                while (scan.hasNextLine()) {
//                    serverFile = scan.nextLine(); // get server name from txt file
//                    userNameFile = scan.nextLine(); // get user name from txt file
//                    passwordFile = scan.nextLine(); // get password from txt file
//                    dbName = scan.nextLine(); // get db name from txt file
//                    zktPath = scan.nextLine(); // get zkt file path
//                    rtaPath = scan.nextLine(); // get rta file path
//
//                    zktPath = zktPath.substring(4, zktPath.length());
//                    System.out.println(zktPath);
//                    rtaPath = rtaPath.substring(4, rtaPath.length());
//                }
//                System.out.println(rtaPath);
//            }
//            scan.close();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(SetupDatabase.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtServerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jBtnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTxtDbName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnChoseZktDatabaseLink = new javax.swing.JButton();
        lblFileNameZkt = new javax.swing.JLabel();
        btnChoseRTAdatabaseLink = new javax.swing.JButton();
        lblFileNameRta = new javax.swing.JLabel();

        setTitle("Setup");
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 224));

        jLabel1.setText("SQL Server Name:");

        jTxtServerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtServerNameKeyPressed(evt);
            }
        });

        jLabel2.setText("SQL Server User Name:");

        jTxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyPressed(evt);
            }
        });

        jBtnSave.setText("Save");
        jBtnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 51), null, null));
        jBtnSave.setContentAreaFilled(false);
        jBtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("SQL Server Password:");

        jTxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPasswordKeyPressed(evt);
            }
        });

        jLabel4.setText("SQL Server DB Name:");

        jTxtDbName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtDbNameKeyPressed(evt);
            }
        });

        jLabel5.setText("RTA Database Link");

        jLabel6.setText("ZKT Database Link");

        btnChoseZktDatabaseLink.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btnChoseZktDatabaseLink.setText("Chose");
        btnChoseZktDatabaseLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseZktDatabaseLinkActionPerformed(evt);
            }
        });

        lblFileNameZkt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnChoseRTAdatabaseLink.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btnChoseRTAdatabaseLink.setText("Chose");
        btnChoseRTAdatabaseLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseRTAdatabaseLinkActionPerformed(evt);
            }
        });

        lblFileNameRta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtServerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFileNameZkt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChoseZktDatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblFileNameRta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnChoseRTAdatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxtUserName)
                    .addComponent(lblFileNameZkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChoseZktDatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxtPassword)
                    .addComponent(lblFileNameRta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChoseRTAdatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        PasswordEnqDnq enqDnq=new PWS();
        
        if (jTxtServerName.getText() != null) {

            try (OutputStream out = new FileOutputStream("config.properties")) {

                Properties properties = new Properties();
                
                properties.setProperty(keyList.KEY_SERVER_NAME, jTxtServerName.getText());
                properties.setProperty(keyList.KEY_USER_NAME, jTxtUserName.getText());
                properties.setProperty(keyList.KEY_USER_PASSWORD, enqDnq.passwordEnq(jTxtPassword.getText()));
                properties.setProperty(keyList.KEY_DATABSE_NAME, jTxtDbName.getText());
                if (zktDatabaseLink==null) {
                    properties.setProperty(keyList.KEY_ZKT_LINK, zktPath);
                } else {
                    properties.setProperty(keyList.KEY_ZKT_LINK, zktDatabaseLink);
                }
                if (rtaDatabaseLink==null) {
                    properties.setProperty(keyList.KEY_RTA_LINK, rtaPath);
                } else {
                    properties.setProperty(keyList.KEY_RTA_LINK, rtaDatabaseLink);
                }
                
                properties.store(out, "Update-Database-Info");
                properties.clear();

                JOptionPane.showMessageDialog(
                        null, " Data Save ",
                        ":: Date Converting Success :: ", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(
                        null, "Check File Exists? " + e.getMessage(),
                        ":: File Not Found :: ", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jTxtServerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtServerNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxtUserName.requestFocus();
        }
    }//GEN-LAST:event_jTxtServerNameKeyPressed

    private void jTxtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxtPassword.requestFocus();
        }
    }//GEN-LAST:event_jTxtUserNameKeyPressed

    private void jTxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxtDbName.requestFocus();
        }
    }//GEN-LAST:event_jTxtPasswordKeyPressed

    private void jTxtDbNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDbNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnSave.requestFocus();
        }
    }//GEN-LAST:event_jTxtDbNameKeyPressed

    private void btnChoseZktDatabaseLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseZktDatabaseLinkActionPerformed
        // TODO add your handling code here:
        try {
            // File Chooser for choose file location
            JFileChooser jfc = new JFileChooser();
            jfc.showDialog(null, "Select"); // set file select button.
            jfc.setVisible(true); // view file chooser dialog.
            File filename = jfc.getSelectedFile();
            String filePath = filename.getAbsolutePath();
            lblFileNameZkt.setText(filePath);
            zktDatabaseLink = filePath;
            System.out.println("File name " + filePath);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    ":: Check File Is Exists ? ::", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnChoseZktDatabaseLinkActionPerformed

    private void btnChoseRTAdatabaseLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseRTAdatabaseLinkActionPerformed
        // TODO add your handling code here:
        try {
            // File Chooser for choose file location.
            JFileChooser jfc = new JFileChooser(); // set file select button.
            jfc.showDialog(null, "Select"); // view file chooser dialog.
            jfc.setVisible(true);
            File filename = jfc.getSelectedFile();
            String filePath = filename.getAbsolutePath();
            lblFileNameRta.setText(filePath);
            rtaDatabaseLink = filePath;
            System.out.println("File name " + filePath);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    ":: Check File Is Exists ? ::", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnChoseRTAdatabaseLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoseRTAdatabaseLink;
    private javax.swing.JButton btnChoseZktDatabaseLink;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtDbName;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtServerName;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JLabel lblFileNameRta;
    private javax.swing.JLabel lblFileNameZkt;
    // End of variables declaration//GEN-END:variables
}
