/*
 * Copyright (C) 2020 VSI-ANIK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package utility;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author VSI-ANIK
 */
public class SetupDatabase extends javax.swing.JFrame {

    private String zktDatabaseLink;
    private String rtaDatabaseLink;
    private String unisDatabaseLinkAccess;
    private String serverFile;
    private String unisSQLServerName;
    private String userNameFile;
    private String unisUserNameAccess;
    private String unisPasswordAccess;
    private String unisUserNameSQLServer;
    private String unisPasswordSQLServer;
    private String passwordFile;
    private String dbName;
    private String unisSqlServerDBName;
    private String unisAccessServerDBName;
    private String zktPath;
    private String rtaPath;
    private String unisPath;
    private String extraCardnoAddedZkt;
    private String extraCardnoAddedRta;
    private String extraCardnoAddedNitgen;
    private String extraCardnoAddedUnis;
    private KeyList keyList = new KeyList();

    /**
     * Creates new form SetupDatabase
     */
    public SetupDatabase() {
        initComponents();     
        holdOldData();
        
        PasswordEnqDnq enqDnq=new PWS();
        jTxtDbName.setText(dbName);
        jTxtPassword.setText(enqDnq.passwordDnq(passwordFile));
        jTxtServerName.setText(serverFile);
        jTxtUserName.setText(userNameFile);
        jTxtExtraStringForCardnoRTA.setText(extraCardnoAddedRta);
        jTxtExtraStringForCardnoZKT.setText(extraCardnoAddedZkt);
        jTxtExtraStringForCardnoNITGEN.setText(extraCardnoAddedNitgen);
    }

    private void holdOldData() {

//        try {
        try (InputStream input = new FileInputStream("config.properties")) {

            Properties properties = new Properties();
            properties.load(input);
            serverFile = properties.getProperty(keyList.KEY_SERVER_NAME);
            userNameFile = properties.getProperty(keyList.KEY_USER_NAME);
            passwordFile = properties.getProperty(keyList.KEY_USER_PASSWORD);
            dbName = properties.getProperty(keyList.KEY_DATABSE_NAME);
            zktPath = properties.getProperty(keyList.KEY_ZKT_LINK);
            rtaPath = properties.getProperty(keyList.KEY_RTA_LINK);
            extraCardnoAddedZkt = properties.getProperty(keyList.KEY_CARDNO_EXTRA_ADDED_ZKT);
            extraCardnoAddedRta = properties.getProperty(keyList.KEY_CARDNO_EXTRA_ADDED_RTA);
            extraCardnoAddedNitgen = properties.getProperty(keyList.KEY_CARDNO_EXTRA_ADDED_NTGEN);

            properties.clear();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    null, "Check File Exists? Or Save Information",
                    ":: File Not Found ::", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnChoseUnisDatabaseLink = new javax.swing.JButton();
        txtServerNameUnis = new javax.swing.JTextField();
        txtPasswordUnisAccess = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtExtraStringForCardnoUNIS = new javax.swing.JTextField();
        txtPasswordUnis = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtUserNameUnis = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblFileNameUnis = new javax.swing.JLabel();
        txtUserNameUnisAccess = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTxtExtraStringForCardnoRTA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnChoseRTAdatabaseLink = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblFileNameRta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFileNameZkt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnChoseZktDatabaseLink = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTxtExtraStringForCardnoZKT = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTxtServerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jTxtExtraStringForCardnoNITGEN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jTxtDbName = new javax.swing.JTextField();

        setTitle("Setup");
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 224));

        jBtnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSave.setText("Save");
        jBtnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 204, 51), null, null));
        jBtnSave.setContentAreaFilled(false);
        jBtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jLabel15.setText("UNIS Database Link (Access)");

        btnChoseUnisDatabaseLink.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btnChoseUnisDatabaseLink.setText("Chose");
        btnChoseUnisDatabaseLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseUnisDatabaseLinkActionPerformed(evt);
            }
        });

        txtServerNameUnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtServerNameUnisKeyPressed(evt);
            }
        });

        txtPasswordUnisAccess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordUnisAccessKeyPressed(evt);
            }
        });

        jLabel17.setText("UNIS DB Password (Access)");

        jLabel12.setText("SQL Server Name [UNIS]:");

        jLabel10.setText("SQL Server Password[UNIS]:");

        jTxtExtraStringForCardnoUNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtExtraStringForCardnoUNISKeyPressed(evt);
            }
        });

        txtPasswordUnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordUnisKeyPressed(evt);
            }
        });

        jLabel14.setText("Extra String Cardno [UNIS]:");

        jLabel16.setText("UNIS DB Username (Access)");

        txtUserNameUnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameUnisKeyPressed(evt);
            }
        });

        jLabel11.setText("SQL Server UserName [UNIS]:");

        lblFileNameUnis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtUserNameUnisAccess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameUnisAccessKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtExtraStringForCardnoUNIS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServerNameUnis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordUnis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserNameUnis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPasswordUnisAccess, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserNameUnisAccess, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblFileNameUnis, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnChoseUnisDatabaseLink))))
                        .addGap(8, 8, 8))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(txtPasswordUnisAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFileNameUnis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnChoseUnisDatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtUserNameUnisAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtExtraStringForCardnoUNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(txtServerNameUnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserNameUnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(txtPasswordUnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTxtExtraStringForCardnoRTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtExtraStringForCardnoRTAKeyPressed(evt);
            }
        });

        jLabel5.setText("RTA Database Link (Access)");

        btnChoseRTAdatabaseLink.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btnChoseRTAdatabaseLink.setText("Chose");
        btnChoseRTAdatabaseLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseRTAdatabaseLinkActionPerformed(evt);
            }
        });

        jLabel7.setText("Extra String Cardno RTA");

        lblFileNameRta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtExtraStringForCardnoRTA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblFileNameRta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChoseRTAdatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileNameRta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoseRTAdatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtExtraStringForCardnoRTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblFileNameZkt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Extra String Cardno ZKT");

        btnChoseZktDatabaseLink.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btnChoseZktDatabaseLink.setText("Chose");
        btnChoseZktDatabaseLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseZktDatabaseLinkActionPerformed(evt);
            }
        });

        jLabel6.setText("ZKT Database Link (Access)");

        jTxtExtraStringForCardnoZKT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtExtraStringForCardnoZKTKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblFileNameZkt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChoseZktDatabaseLink))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtExtraStringForCardnoZKT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileNameZkt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoseZktDatabaseLink, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(jTxtExtraStringForCardnoZKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTxtServerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtServerNameKeyPressed(evt);
            }
        });

        jLabel4.setText("SQL Server DB Name[NITGEN]:");

        jLabel1.setText("SQL Server Name [NITGEN]:");

        jLabel9.setText("Extra String Cardno NITGEN");

        jTxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyPressed(evt);
            }
        });

        jTxtExtraStringForCardnoNITGEN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtExtraStringForCardnoNITGENKeyPressed(evt);
            }
        });

        jLabel3.setText("SQL Server Password[NITGEN]:");

        jLabel2.setText("SQL Server UserName [NITGEN]:");

        jTxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPasswordKeyPressed(evt);
            }
        });

        jTxtDbName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtDbNameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTxtDbName)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtExtraStringForCardnoNITGEN))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtExtraStringForCardnoNITGEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        PasswordEnqDnq enqDnq = new PWS();

        if (jTxtServerName.getText() != null) {

            try (OutputStream out = new FileOutputStream("config.properties")) {

                Properties properties = new Properties();

                properties.setProperty(keyList.KEY_SERVER_NAME, jTxtServerName.getText());
                properties.setProperty(keyList.KEY_USER_NAME, jTxtUserName.getText());
                properties.setProperty(keyList.KEY_USER_PASSWORD, jTxtPassword.getText());
                properties.setProperty(keyList.KEY_DATABSE_NAME, jTxtDbName.getText());
                properties.setProperty(keyList.KEY_CARDNO_EXTRA_ADDED_ZKT, jTxtExtraStringForCardnoZKT.getText());
                properties.setProperty(keyList.KEY_CARDNO_EXTRA_ADDED_RTA, jTxtExtraStringForCardnoRTA.getText());
                properties.setProperty(keyList.KEY_CARDNO_EXTRA_ADDED_NTGEN, jTxtExtraStringForCardnoNITGEN.getText());
                properties.setProperty(keyList.KEY_SQL_SERVER_NAME_UNIS, txtServerNameUnis.getText());
                properties.setProperty(keyList.KEY_USER_NAME_SQLSERVER_UNIS, txtUserNameUnis.getText());
                properties.setProperty(keyList.KEY_PASSWORD_SQLSERVER_UNIS, txtPasswordUnis.getText());
                properties.setProperty(keyList.KEY_USER_NAME_ACCESS_UNIS, txtUserNameUnisAccess.getText());
                properties.setProperty(keyList.KEY_PASSWORD_ACCESS_UNIS, txtPasswordUnisAccess.getText());
                

                if (zktDatabaseLink == null) {
                    properties.setProperty(keyList.KEY_ZKT_LINK, zktPath);
                } else {
                    properties.setProperty(keyList.KEY_ZKT_LINK, zktDatabaseLink);
                }
                if (rtaDatabaseLink == null) {
                    properties.setProperty(keyList.KEY_RTA_LINK, rtaPath);
                } else {
                    properties.setProperty(keyList.KEY_RTA_LINK, rtaDatabaseLink);
                }
                if(unisDatabaseLinkAccess == null){
                   properties.setProperty(keyList.KEY_UNIS_ACCESS_DB_LINK, unisDatabaseLinkAccess);
                }

                properties.store(out, "Update-Database-Info");
                properties.clear();

                JOptionPane.showMessageDialog(
                        null, " Data Save ",
                        ":: Date Converting Success :: ", JOptionPane.INFORMATION_MESSAGE);
                

            } catch (IOException e) {
                JOptionPane.showMessageDialog(
                        null, "Check File Exists? " + e.getMessage(),
                        ":: File Not Found :: ", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jTxtServerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtServerNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxtUserName.requestFocus();
        }
    }//GEN-LAST:event_jTxtServerNameKeyPressed

    private void jTxtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxtPassword.requestFocus();
        }
    }//GEN-LAST:event_jTxtUserNameKeyPressed

    private void jTxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTxtDbName.requestFocus();
        }
    }//GEN-LAST:event_jTxtPasswordKeyPressed

    private void jTxtDbNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDbNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnSave.requestFocus();
        }
    }//GEN-LAST:event_jTxtDbNameKeyPressed

    private void btnChoseZktDatabaseLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseZktDatabaseLinkActionPerformed
        // TODO add your handling code here:
        try {
            // File Chooser for choose file location
            JFileChooser jfc = new JFileChooser();
            jfc.showDialog(null, "Select"); // set file select button.
            jfc.setVisible(true); // view file chooser dialog.
            File filename = jfc.getSelectedFile();
            String filePath = filename.getAbsolutePath();
            lblFileNameZkt.setText(filePath);
            zktDatabaseLink = filePath;
            System.out.println("File name " + filePath);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    ":: Check File Is Exists ? ::", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnChoseZktDatabaseLinkActionPerformed

    private void btnChoseRTAdatabaseLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseRTAdatabaseLinkActionPerformed
        // TODO add your handling code here:
        try {
            // File Chooser for choose file location.
            JFileChooser jfc = new JFileChooser(); // set file select button.
            jfc.showDialog(null, "Select"); // view file chooser dialog.
            jfc.setVisible(true);
            File filename = jfc.getSelectedFile();
            String filePath = filename.getAbsolutePath();
            lblFileNameRta.setText(filePath);
            rtaDatabaseLink = filePath;
            System.out.println("File name " + filePath);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    ":: Check File Is Exists ? ::", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnChoseRTAdatabaseLinkActionPerformed

    private void jTxtExtraStringForCardnoRTAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtExtraStringForCardnoRTAKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtExtraStringForCardnoRTAKeyPressed

    private void jTxtExtraStringForCardnoZKTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtExtraStringForCardnoZKTKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtExtraStringForCardnoZKTKeyPressed

    private void jTxtExtraStringForCardnoNITGENKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtExtraStringForCardnoNITGENKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtExtraStringForCardnoNITGENKeyPressed

    private void txtPasswordUnisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordUnisKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordUnisKeyPressed

    private void txtUserNameUnisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameUnisKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameUnisKeyPressed

    private void txtServerNameUnisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServerNameUnisKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerNameUnisKeyPressed

    private void jTxtExtraStringForCardnoUNISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtExtraStringForCardnoUNISKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtExtraStringForCardnoUNISKeyPressed

    private void btnChoseUnisDatabaseLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseUnisDatabaseLinkActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            // File Chooser for choose file location
            JFileChooser jfc = new JFileChooser();
            jfc.showDialog(null, "Select"); // set file select button.
            jfc.setVisible(true); // view file chooser dialog.
            File filename = jfc.getSelectedFile();
            String filePath = filename.getAbsolutePath();
            lblFileNameUnis.setText(filePath);
            unisDatabaseLinkAccess = filePath;
            System.out.println("File name " + filePath);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    ":: Check File Is Exists ? ::", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnChoseUnisDatabaseLinkActionPerformed

    private void txtPasswordUnisAccessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordUnisAccessKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordUnisAccessKeyPressed

    private void txtUserNameUnisAccessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameUnisAccessKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameUnisAccessKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoseRTAdatabaseLink;
    private javax.swing.JButton btnChoseUnisDatabaseLink;
    private javax.swing.JButton btnChoseZktDatabaseLink;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTxtDbName;
    private javax.swing.JTextField jTxtExtraStringForCardnoNITGEN;
    private javax.swing.JTextField jTxtExtraStringForCardnoRTA;
    private javax.swing.JTextField jTxtExtraStringForCardnoUNIS;
    private javax.swing.JTextField jTxtExtraStringForCardnoZKT;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtServerName;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JLabel lblFileNameRta;
    private javax.swing.JLabel lblFileNameUnis;
    private javax.swing.JLabel lblFileNameZkt;
    private javax.swing.JPasswordField txtPasswordUnis;
    private javax.swing.JTextField txtPasswordUnisAccess;
    private javax.swing.JTextField txtServerNameUnis;
    private javax.swing.JTextField txtUserNameUnis;
    private javax.swing.JTextField txtUserNameUnisAccess;
    // End of variables declaration//GEN-END:variables
}
