/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.filefinder.view;

import com.filefinder.utility.DaoFileNameList;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VSI-ANIK
 */
public class MainScreen extends javax.swing.JFrame {

    private List<DaoFileNameList> nameList = new ArrayList<>();
    private String lists[];
    private File fileList[];
    private String fileWorkingPath = "D:\\Req._Change\\";
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY");
    private String selectedFilePath;
    private int selectedFileIndex;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        showFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowFileList = new javax.swing.JTable();
        comboShowComapnyList = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        comboShowReqDate = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblShowFileList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblShowFileList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "SL", "Company", "Req Date", "Check"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShowFileList.setToolTipText("");
        tblShowFileList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblShowFileList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblShowFileList.setRowHeight(30);
        tblShowFileList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowFileListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShowFileList);
        if (tblShowFileList.getColumnModel().getColumnCount() > 0) {
            tblShowFileList.getColumnModel().getColumn(0).setResizable(false);
            tblShowFileList.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblShowFileList.getColumnModel().getColumn(1).setResizable(false);
            tblShowFileList.getColumnModel().getColumn(2).setResizable(false);
            tblShowFileList.getColumnModel().getColumn(3).setResizable(false);
        }

        comboShowComapnyList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboShowComapnyList.setMaximumRowCount(100);
        comboShowComapnyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboShowComapnyListActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        btnSubmit.setText("Job Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboShowReqDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboShowReqDate.setMaximumRowCount(100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboShowComapnyList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboShowReqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboShowComapnyList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(comboShowReqDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public List<DaoFileNameList> findFile() {

        File file = new File(fileWorkingPath);

        lists = file.list();
        fileList = file.listFiles();

        for (int i = 0; i < lists.length; i++) {
            DaoFileNameList dfnl = new DaoFileNameList();
            Date date = new Date(fileList[i].lastModified());
            System.out.println(lists[i] + "   Date: " + format.format(date));
            dfnl.setSlNo(i);
            dfnl.setFileName(lists[i]);
            dfnl.setFileModifactionDate(date);
            String status = "Nil";
            try {
                String path = fileWorkingPath + lists[i] + "\\log.txt";
                File f = new File(path);
                Scanner scanner = new Scanner(f);
                status = scanner.nextLine();
                System.out.println(status);
                scanner.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            dfnl.setIsSubmited(status);

            nameList.add(dfnl);
        }
        return nameList;
    }

    
    
    public void showFile() {
        List<DaoFileNameList> dfnls = findFile();
        DefaultTableModel model = (DefaultTableModel) tblShowFileList.getModel();
        Object row[] = new Object[4];

        for (int i = 0; i < dfnls.size(); i++) {
            row[0] = dfnls.get(i).getSlNo();
            row[1] = dfnls.get(i).getFileName();
            row[2] = format.format(dfnls.get(i).getFileModifactionDate());
            row[3] = dfnls.get(i).getIsSubmited();
            model.addRow(row);
            comboShowComapnyList.addItem(dfnls.get(i).getSlNo() + " " + dfnls.get(i).getFileName());
            comboShowReqDate.addItem(format.format(dfnls.get(i).getFileModifactionDate()));
        }

    }


    private void comboShowComapnyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboShowComapnyListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboShowComapnyListActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String texts[] = comboShowComapnyList.getSelectedItem().toString().split(" ");
        selectedFileIndex = Integer.parseInt(texts[0]);
        for (int i = 0; i < nameList.size(); i++) {
            if (nameList.get(i).getSlNo() == selectedFileIndex) {
                selectedFilePath = fileWorkingPath + nameList.get(i).getFileName() + "\\log.txt";
                System.out.println(nameList.get(i).getFileName());
                System.out.println(selectedFilePath);
                try {
                    PrintWriter pw = new PrintWriter(selectedFilePath);
                    pw.println("OK");
                    pw.println("OK");
                    pw.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
        }

        try {
            File f = new File(selectedFilePath);
            Scanner scanner = new Scanner(f);
            System.out.println(scanner.nextLine());
            System.out.println(scanner.nextLine());
            scanner.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void tblShowFileListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowFileListMouseClicked
        // TODO add your handling code here:
        String loc = fileWorkingPath + nameList.get(tblShowFileList.getSelectedRow()-1).getFileName() + "\\";
        System.out.println("\n=> "+loc);
        new PanddingList(loc).setVisible(true);

    }//GEN-LAST:event_tblShowFileListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboShowComapnyList;
    private javax.swing.JComboBox<String> comboShowReqDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblShowFileList;
    // End of variables declaration//GEN-END:variables
}
